# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib
, php
, phpPackages
, unzip
, stdenv
, runCommandLocal
, writeText
, fetchurl

  # Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let
  data = builtins.fromJSON ''
        {
        "cacheEntries": [
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nikic_php-parser-4.15.2.0",
                "urls": [
                    "https://api.github.com/repos/nikic/PHP-Parser/zipball/f59bbe44bf7d96f24f3e2b4ddc21cd52c1d2adbc"
                ],
                "cacheFile": "nikic/php-parser/e236b4c6515233fbea34d00815dd48192bfd54f1.zip",
                "sha256": "b543992555ebe12789282ff5ae2037eff819ec5246b5d2f5dec1072f8b485c53"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-1.9.4.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan/zipball/d03bccee595e2146b7c9d174486b84f4dc61b0f2"
                ],
                "cacheFile": "phpstan/phpstan/a4d0abfecf2a858deed1be8c1b16d8e50708792d.zip",
                "sha256": "38c0326d482bc2c545bd5d912da2b7907706ca86293ffe2695244e03cb55487f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "amphp_amp-2.6.2.0",
                "urls": [
                    "https://api.github.com/repos/amphp/amp/zipball/9d5100cebffa729aaffecd3ad25dc5aeea4f13bb"
                ],
                "cacheFile": "amphp/amp/8c9c2a2bf8be8fda4a26bfe6c6e261d39b6b0320.zip",
                "sha256": "c15688dd5756771bb52c1c30f9088327cc49ffb69131183d05b0642e7a4f935f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "amphp_byte-stream-1.8.1.0",
                "urls": [
                    "https://api.github.com/repos/amphp/byte-stream/zipball/acbd8002b3536485c997c4e019206b3f10ca15bd"
                ],
                "cacheFile": "amphp/byte-stream/24823ac0e49e56800f97cb0f4e852334fc3a60e0.zip",
                "sha256": "227fbf5650a188d0e7da15b61642bc2a076ed7cd293f20f92205eff862615892"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "brick_varexporter-0.3.7.0",
                "urls": [
                    "https://api.github.com/repos/brick/varexporter/zipball/3e263cd718d242594c52963760fee2059fd5833c"
                ],
                "cacheFile": "brick/varexporter/3db8947f6c3da0acd7fea124189ad13998d24e5f.zip",
                "sha256": "2c5ab28e3c0966def2a7cd1065da83b33a8afedd4b597608b73fd8cf42eee5d6"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_package-versions-deprecated-1.11.99.5",
                "urls": [
                    "https://api.github.com/repos/composer/package-versions-deprecated/zipball/b4f54f74ef3453349c24a845d22392cd31e65f1d"
                ],
                "cacheFile": "composer/package-versions-deprecated/7696d631625b248d150b3db3037b6fb36a2f1cf1.zip",
                "sha256": "557187e1f72faff2b2e61fedd93824c74b491f6078c8135fe2978488e6ee32c3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_pcre-3.1.0.0",
                "urls": [
                    "https://api.github.com/repos/composer/pcre/zipball/4bff79ddd77851fe3cdd11616ed3f92841ba5bd2"
                ],
                "cacheFile": "composer/pcre/16ea22f0a3bddd3c7683dfc2378869ab617d3036.zip",
                "sha256": "3aff2a08d578d70c7b1f78553de1962f39a973097dee9bb0e46372358b589b15"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_semver-3.3.2.0",
                "urls": [
                    "https://api.github.com/repos/composer/semver/zipball/3953f23262f2bff1919fc82183ad9acb13ff62c9"
                ],
                "cacheFile": "composer/semver/29fa63f52104d4c4bf687735fbaaf52f0a232c4b.zip",
                "sha256": "baaee53811af1c73fa17da54c1722c888207008eac70d0f239073fb13e24e56a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_xdebug-handler-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/composer/xdebug-handler/zipball/ced299686f41dce890debac69273b47ffe98a40c"
                ],
                "cacheFile": "composer/xdebug-handler/524bae0e78ed4946a977f22dc3ff8629f96dfaf7.zip",
                "sha256": "102c6388c487229bbedce718465f5b6bb125c20a655066ae967fcc6ac4cdd0c2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dnoegel_php-xdg-base-dir-0.1.1.0",
                "urls": [
                    "https://api.github.com/repos/dnoegel/php-xdg-base-dir/zipball/8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd"
                ],
                "cacheFile": "dnoegel/php-xdg-base-dir/b81b493e09050800919750bdd1e829656fc89971.zip",
                "sha256": "d881707cf02a8aa1a1846e0166e0b1704eeacac059f08a7ec48b593e3959c40a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_inflector-2.0.6.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/inflector/zipball/d9d313a36c872fd6ee06d9a6cbcf713eaa40f024"
                ],
                "cacheFile": "doctrine/inflector/57c027282263baa14000cf3525eb68a5f0795e45.zip",
                "sha256": "12dae3b88886e0adde83b1d7338d2df7480620a0ec5ec8cde15935857b05defc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_instantiator-1.4.1.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/instantiator/zipball/10dcfce151b967d20fde1b34ae6640712c3891bc"
                ],
                "cacheFile": "doctrine/instantiator/b6977602bc07407dd2e3c71223021731d80df6d6.zip",
                "sha256": "e74aae2efad779dc6044b0b5d3ac4cf56eb41a511549ed35e6046cb4d6e0d7d4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_lexer-1.2.3.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/lexer/zipball/c268e882d4dbdd85e36e4ad69e02dc284f89d229"
                ],
                "cacheFile": "doctrine/lexer/4ab8440502eac4ce094502573b529bcbae3991e3.zip",
                "sha256": "1a329ce6ee5b48d38f7455631d0f9abd122643b304a112a6a76a50496d32e089"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "egulias_email-validator-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/egulias/EmailValidator/zipball/f88dcf4b14af14a98ad96b14b2b317969eab6715"
                ],
                "cacheFile": "egulias/email-validator/6057c080143c0fb488917f6bcf0c04e4322f12a5.zip",
                "sha256": "b19dfc81a404989412dd7aa64fdcedbe3f8d57f325327e88e95ab9881a2004f0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "felixfbecker_advanced-json-rpc-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/felixfbecker/php-advanced-json-rpc/zipball/b5f37dbff9a8ad360ca341f3240dc1c168b45447"
                ],
                "cacheFile": "felixfbecker/advanced-json-rpc/ee93f6a030a8ec4909ae17405ed90c75f9d0c59c.zip",
                "sha256": "98b15c828413b99ecd0670f91ee25eea5ac9453d5507b2d63711dabf44982490"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "felixfbecker_language-server-protocol-1.5.2.0",
                "urls": [
                    "https://api.github.com/repos/felixfbecker/php-language-server-protocol/zipball/6e82196ffd7c62f7794d778ca52b69feec9f2842"
                ],
                "cacheFile": "felixfbecker/language-server-protocol/bee555c8048b240c2c2f28255fef8f3efc814e2c.zip",
                "sha256": "67502ffec7d734cd69d724ef6dca52f40dc7f23752d021b61e384656a86d343e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fidry_cpu-core-counter-0.4.1.0",
                "urls": [
                    "https://api.github.com/repos/theofidry/cpu-core-counter/zipball/79261cc280aded96d098e1b0e0ba0c4881b432c2"
                ],
                "cacheFile": "fidry/cpu-core-counter/50cd15d7ea524aa7ec47ca26b5e85018cf20893e.zip",
                "sha256": "80f8431805509472afa824d56d19e8b36421febb671dbf1a498de9946e79e437"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fruitcake_php-cors-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/fruitcake/php-cors/zipball/58571acbaa5f9f462c9c77e911700ac66f446d4e"
                ],
                "cacheFile": "fruitcake/php-cors/1de04ebee01b584ebc4c86dacbf172b3bc4ee77a.zip",
                "sha256": "a16a913bc20cbd2a26b114975e324dde53e897f068a4fbb8c33fcd467032b5a3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_collections-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/collections/zipball/7a8afa0875d7de162f30865d9fae33c8fb235fa2"
                ],
                "cacheFile": "illuminate/collections/13a587d92a296d99ad577bd79cbf3f473e1f39b4.zip",
                "sha256": "0f6a4b63c9ca375f496e974fe3218d9d3586029149ca53041987d0398b9d5683"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_conditionable-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/conditionable/zipball/5b40f51ccb07e0e7b1ec5559d8db9e0e2dc51883"
                ],
                "cacheFile": "illuminate/conditionable/3d13d9225d1c36a43c88c6e5eaa776bc5c76c77a.zip",
                "sha256": "5e00880e76d178d1a8235bdc062c3a89506d1b575bb3eecfa36d55911a719ece"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_container-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/container/zipball/8ca3036459e26dc7cdedaf0f882b625757cc341e"
                ],
                "cacheFile": "illuminate/container/01bafe3a7b4ae717d4c741b97e1607a785e0d84f.zip",
                "sha256": "8d479f5f3208379340b1bb751656f1b260297e8cb446556068b4c57d7c79a55e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_contracts-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/contracts/zipball/c7cc6e6198cac6dfdead111f9758de25413188b7"
                ],
                "cacheFile": "illuminate/contracts/786d93b99d549197e478f991390e03afc6c8b4ca.zip",
                "sha256": "7dc254e5d9eef76571cc101f5b9e764c7050385820d2244776976f7c2c679fe4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_filesystem-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/filesystem/zipball/9923cb717f5505b84200fb78feba1c2f2fe9fe83"
                ],
                "cacheFile": "illuminate/filesystem/fa4ff31eae43441b60ce3eaafa088332ea7e9084.zip",
                "sha256": "8302cdc6f9431d8b7a595ec56f8473c793b11105e39258f69992e99d3c64c3bb"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_http-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/http/zipball/5a0284d6bff14a233c2280f0782be4b5bc6b03ab"
                ],
                "cacheFile": "illuminate/http/5b3cdbab7307976bab81ac78bca4d4f2777167e4.zip",
                "sha256": "59b35c3a6605b5b138ca5faef51b00a8aadc4925f4881a872c77117f2198f64c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_macroable-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/macroable/zipball/e3bfaf6401742a9c6abca61b9b10e998e5b6449a"
                ],
                "cacheFile": "illuminate/macroable/795f18e284aa50b093375bcd385436881c49282f.zip",
                "sha256": "5dd68acf1817fb2f7795c60b5f4aa76c66a174241bef5e92c9a7c799b6e2b463"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_session-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/session/zipball/1e5d31bf7c6ed5844cedd4c36cf8251ec677309e"
                ],
                "cacheFile": "illuminate/session/f34f64440bcf490d2389432f7cd8298ccdf509c5.zip",
                "sha256": "c416054ca674eec9aff4dcb490995ba3ae5b96b58b34990da36b5167bd5bddeb"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_support-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/support/zipball/d7f7c07e35a2c09cbeeddc0168826cf05a2eeb84"
                ],
                "cacheFile": "illuminate/support/13ebdd3898bf52dcde91894ece6e7d7bd5da586a.zip",
                "sha256": "33d507b5c3d7b8afd3a8a23b104995afca7d399667e7498f22d71090e22c086a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_translation-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/translation/zipball/53d0cd548a8ad64eaf12d539bf39ee4189dcee56"
                ],
                "cacheFile": "illuminate/translation/4d884098d898f155018573c240a70466ae426a20.zip",
                "sha256": "763c454824d61d6a6a231bbacf4d50e044def5b3a270791e58774f20c90db23f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_validation-9.45.1.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/validation/zipball/a0f19e0bb4b4896b04b34a875d569c61b3b00ace"
                ],
                "cacheFile": "illuminate/validation/7813d50920d50084dcb6645d8bd3068af3b60b88.zip",
                "sha256": "7e7d0a21190c59b31df0a7447d75f8bdec9605a661809f3d6e4623b061c78a69"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "monolog_monolog-2.8.0.0",
                "urls": [
                    "https://api.github.com/repos/Seldaek/monolog/zipball/720488632c590286b88b80e62aa3d3d551ad4a50"
                ],
                "cacheFile": "monolog/monolog/8be15cb4c5912b19f2b030398fe4b7c51e6d3b5a.zip",
                "sha256": "c6c5ccd79c8e3b5f16be516bc1facb493ba98c5e5bb1972e332b42f82af0e171"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "myclabs_deep-copy-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614"
                ],
                "cacheFile": "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip",
                "sha256": "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nesbot_carbon-2.64.0.0",
                "urls": [
                    "https://api.github.com/repos/briannesbitt/Carbon/zipball/889546413c97de2d05063b8cb7b193c2531ea211"
                ],
                "cacheFile": "nesbot/carbon/be5f2779e67997abb68a2aa35696618a18e6ed7f.zip",
                "sha256": "50f769042e92f9cbff5a7509e4fc93e8dc20b18fb1b1480ae9d7115d8393f866"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "netresearch_jsonmapper-4.1.0.0",
                "urls": [
                    "https://api.github.com/repos/cweiske/jsonmapper/zipball/cfa81ea1d35294d64adb9c68aa4cb9e92400e53f"
                ],
                "cacheFile": "netresearch/jsonmapper/d2d7958f1c477df80307bcdeee9e2301dfdca0d9.zip",
                "sha256": "1f2c48574155a7c23b6b2735fb8e2cb4480dbed6bc990cb1c27ad2638dc29ec2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_manifest-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53"
                ],
                "cacheFile": "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip",
                "sha256": "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_version-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74"
                ],
                "cacheFile": "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip",
                "sha256": "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_reflection-common-2.2.0.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/ReflectionCommon/zipball/1d01c49d4ed62f25aa84a747ad35d5a16924662b"
                ],
                "cacheFile": "phpdocumentor/reflection-common/6243ab17e2330fb7ce63d34391d53104cc913dc0.zip",
                "sha256": "39fca6dc8730bdc4f70c41e58e16595fc6695b4ae42327c32144c4131410a7f3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_reflection-docblock-5.3.0.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/ReflectionDocBlock/zipball/622548b623e81ca6d78b721c5e029f4ce664f170"
                ],
                "cacheFile": "phpdocumentor/reflection-docblock/3c16e706c93df7017840bcf302eace70dc66a077.zip",
                "sha256": "3664230b09277d49780b0cb8f0a4a324e061f4bad079ac015b49a3892f7440ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_type-resolver-1.6.2.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/TypeResolver/zipball/48f445a408c131e38cab1c235aa6d2bb7a0bb20d"
                ],
                "cacheFile": "phpdocumentor/type-resolver/96bd30e4a669e3eb8e7ff86ae5bd2289737026e6.zip",
                "sha256": "cdaa0d67bc01ab4aeb3361a424e6cd716ef229422b63b4f7b425a6afba4de1f9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-php-parser-1.1.0.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-php-parser/zipball/1c7670dd92da864b5d019f22d9f512a6ae18b78e"
                ],
                "cacheFile": "phpstan/phpstan-php-parser/3a60f66030b521425d4ae82eb36a348495b6c779.zip",
                "sha256": "7905d6a8cef6fa2896ff7ce86ec9118addafb9a6e282553bd32957fb6de7bf85"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-phpunit-1.3.3.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-phpunit/zipball/54a24bd23e9e80ee918cdc24f909d376c2e273f7"
                ],
                "cacheFile": "phpstan/phpstan-phpunit/a2b06418ffb3fd0045bc553352792c1c792f2735.zip",
                "sha256": "ca935892fd5c35ac059543c667e7723008d5e5f93857ee77d9cb89c4168df497"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-strict-rules-1.4.4.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-strict-rules/zipball/23e5f377ee6395a1a04842d3d6ed4bd25e7b44a6"
                ],
                "cacheFile": "phpstan/phpstan-strict-rules/997a5c0a09e643195ce794bceaa3be9bc4773446.zip",
                "sha256": "c0103423e602842128eab01cf11757632b44b1551432aec41ba2db6f7939b4bb"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-code-coverage-9.2.22.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/e4bf60d2220b4baaa0572986b5d69870226b06df"
                ],
                "cacheFile": "phpunit/php-code-coverage/bb67af0d46f41b3dbaaf3ecd84a4266f7bf5cc3f.zip",
                "sha256": "3b198dc52463c9921683f579fa6e717bdda9fe57e837e828b2ed56db3596cbbe"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-file-iterator-3.0.6.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf"
                ],
                "cacheFile": "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip",
                "sha256": "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-invoker-3.1.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67"
                ],
                "cacheFile": "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip",
                "sha256": "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-text-template-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28"
                ],
                "cacheFile": "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip",
                "sha256": "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-timer-5.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2"
                ],
                "cacheFile": "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip",
                "sha256": "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_phpunit-9.5.27.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/a2bc7ffdca99f92d959b3f2270529334030bba38"
                ],
                "cacheFile": "phpunit/phpunit/6acbe1960f94f7c630f0ff374ce6653259ded50e.zip",
                "sha256": "17c65696011dffae85aacbf4d1995432f70ea02bd0bc15afb1c6c1b0c708e65b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_container-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
                ],
                "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
                "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_event-dispatcher-1.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/event-dispatcher/zipball/dbefd12671e8a14ec7f180cab83036ed26714bb0"
                ],
                "cacheFile": "psr/event-dispatcher/8f60a8cd1b7ff4e8f9782d70d78dee877a526529.zip",
                "sha256": "4d6a674cfd89a9957ead82e31ee4df785b2b1d215693add73184729a9a66d116"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_log-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001"
                ],
                "cacheFile": "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip",
                "sha256": "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_simple-cache-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/simple-cache/zipball/764e0b3939f5ca87cb904f570ef9be2d78a07865"
                ],
                "cacheFile": "psr/simple-cache/f30344b376a5fb0289c0491e8df6aba973ba12aa.zip",
                "sha256": "e899e363a85c26b3f1a621182b6eed2a37a71d823410ac949a1cbfd4b655ec41"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_cli-parser-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2"
                ],
                "cacheFile": "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip",
                "sha256": "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-1.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120"
                ],
                "cacheFile": "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip",
                "sha256": "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-reverse-lookup-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5"
                ],
                "cacheFile": "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip",
                "sha256": "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_comparator-4.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a"
                ],
                "cacheFile": "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip",
                "sha256": "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_complexity-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88"
                ],
                "cacheFile": "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip",
                "sha256": "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_diff-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d"
                ],
                "cacheFile": "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip",
                "sha256": "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_environment-5.1.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/environment/zipball/1b5dff7bb151a4db11d49d90e5408e4e938270f7"
                ],
                "cacheFile": "sebastian/environment/0b7f292f62f46ed49ae0d70b39bfa393b4211611.zip",
                "sha256": "2119946edb20c6bde2b716a4c85a0ef2e6ec96abc365c50ffc0044986e551762"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_exporter-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d"
                ],
                "cacheFile": "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip",
                "sha256": "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_global-state-5.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2"
                ],
                "cacheFile": "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip",
                "sha256": "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_lines-of-code-1.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc"
                ],
                "cacheFile": "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip",
                "sha256": "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-enumerator-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71"
                ],
                "cacheFile": "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip",
                "sha256": "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-reflector-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7"
                ],
                "cacheFile": "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip",
                "sha256": "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_recursion-context-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/cd9d8cf3c5804de4341c283ed787f099f5506172"
                ],
                "cacheFile": "sebastian/recursion-context/6458bc6eb2e2dab0f0e7550c596001dd26243950.zip",
                "sha256": "fe429b1e155104d66e0a930e44853d0a3daf790965f0a57712c3609e678813cc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_resource-operations-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8"
                ],
                "cacheFile": "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip",
                "sha256": "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_type-3.2.0.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/type/zipball/fb3fe09c5f0bae6bc27ef3ce933a1e0ed9464b6e"
                ],
                "cacheFile": "sebastian/type/e4452efb1e3255d8306d160c941ba887a0c693b5.zip",
                "sha256": "67748a67088f019de35d5a1213bb1f4e6954b6b20d62a234fef1cd615f4a95d2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_version-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c"
                ],
                "cacheFile": "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip",
                "sha256": "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_array-to-xml-2.17.1.0",
                "urls": [
                    "https://api.github.com/repos/spatie/array-to-xml/zipball/5cbec9c6ab17e320c58a259f0cebe88bde4a7c46"
                ],
                "cacheFile": "spatie/array-to-xml/2d0ab160be3e2ff234108c2f17ad6a074bc4116b.zip",
                "sha256": "a6fd5a96dfad96c685f963e55debd71959b27fd2f82071b91e03d724442a010c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "squizlabs_php_codesniffer-3.7.1.0",
                "urls": [
                    "https://api.github.com/repos/squizlabs/PHP_CodeSniffer/zipball/1359e176e9307e906dc3d890bcc9603ff6d90619"
                ],
                "cacheFile": "squizlabs/php_codesniffer/87828c804599927aa873e78e73b71ea8ed2dc48e.zip",
                "sha256": "41d8bad949966238289179ca65792e9b119fcf650a0e1a1dd7e0f51cbf00eb2d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "stephank_composer-plugin-nixify-9999999-dev",
                "urls": [
                    "https://api.github.com/repos/stephank/composer-plugin-nixify/zipball/fd8faf5b898f5366c9d107eb407360b41a477b8f"
                ],
                "cacheFile": "stephank/composer-plugin-nixify/8d5ce087690933397df5efce3104979209c2852b.zip",
                "sha256": "a207d9fc16be8095ab02e3d30cfd3ce5570f675b01fcf3a9b5df66fc4637ace7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_console-6.0.16.0",
                "urls": [
                    "https://api.github.com/repos/symfony/console/zipball/be294423f337dda97c810733138c0caec1bb0575"
                ],
                "cacheFile": "symfony/console/61b781098586f53d8fb3625580d7eb6fc9a7ef32.zip",
                "sha256": "0ec520094df50eb67af904c6300249bc7d461000f001b7536047242dcd667606"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_deprecation-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/deprecation-contracts/zipball/26954b3d62a6c5fd0ea8a2a00c0353a14978d05c"
                ],
                "cacheFile": "symfony/deprecation-contracts/4d47eca6ee854e21b5f9e5f3b411189f019bd558.zip",
                "sha256": "b70da9d9324b76f55b2ef8afbb11f45c3b59353dcecb27527e55faf56c928af2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_error-handler-6.0.15.0",
                "urls": [
                    "https://api.github.com/repos/symfony/error-handler/zipball/f000c166cb3ee32c4c822831a79260a135cd59b5"
                ],
                "cacheFile": "symfony/error-handler/952e7bd656f968f5fcaba1e3e850f3ab96b302b0.zip",
                "sha256": "a06f24d24e4a03ceeb6219f948d6e583109e0861855fc896ddf85af75bcbccae"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-6.0.9.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher/zipball/5c85b58422865d42c6eb46f7693339056db098a8"
                ],
                "cacheFile": "symfony/event-dispatcher/9582bf9033c87449c80df9f02651a526a390d0fa.zip",
                "sha256": "b78b3945450d3f4b9603ed8e30324ff81abb1df94f40b735fd6d8d61cba6cec5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher-contracts/zipball/7bc61cc2db649b4637d331240c5346dcc7708051"
                ],
                "cacheFile": "symfony/event-dispatcher-contracts/209216ef5d7de22ca666c1d9ae275b3a79137b63.zip",
                "sha256": "91f051a5b67196f07ca500d5b75769cedf9fb24a219dc91d01c9caf288143db3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_filesystem-6.0.13.0",
                "urls": [
                    "https://api.github.com/repos/symfony/filesystem/zipball/3adca49133bd055ebe6011ed1e012be3c908af79"
                ],
                "cacheFile": "symfony/filesystem/58a3ac94d09d20d7cfec12a5234686f704be5dcd.zip",
                "sha256": "66144201313e3982400575ca4fac63d829ae29e81df6d5b2d744915a1bbba1a0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_finder-6.0.11.0",
                "urls": [
                    "https://api.github.com/repos/symfony/finder/zipball/09cb683ba5720385ea6966e5e06be2a34f2568b1"
                ],
                "cacheFile": "symfony/finder/3598a481a079ac63f40f8cf95bf1d2b14764d71d.zip",
                "sha256": "84d8ef4f701ce9c8c4b3be7163c3be592a3937b69c6f29c82b23e1eb7aa6ba2d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-foundation-6.0.16.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-foundation/zipball/86eec2c66d00a2dd03d84352cd10b12df73101ec"
                ],
                "cacheFile": "symfony/http-foundation/e9cb70a91243f9d51c0b70e601a316cd962d05ed.zip",
                "sha256": "402226bfcae0c56e32842461008f8bc15a6fada93e918c7e717dd887cc1a0559"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-kernel-6.0.16.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-kernel/zipball/8ba1344821807ad51f230f0d01e0fa8f366e4abb"
                ],
                "cacheFile": "symfony/http-kernel/2088571a4b62f6cc4f7bd206420b5a9b61335816.zip",
                "sha256": "0d0e20d5d0240b5a29e8c7104b26b729d5c394a23f580e2a4f75e43660f64ef0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_mime-6.0.16.0",
                "urls": [
                    "https://api.github.com/repos/symfony/mime/zipball/ad9878bede5707cdf5ff7f5c86d82a921bbbfe1c"
                ],
                "cacheFile": "symfony/mime/323cc013a76cc14cb3fa67cda87bc32e77ed5b92.zip",
                "sha256": "0d656364bcebd1dc5ec085479060e511182992cb5dfbb7d841d468528d66c428"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-ctype-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a"
                ],
                "cacheFile": "symfony/polyfill-ctype/04e84c03a82a82c09eaa688b17b523570f9d14d2.zip",
                "sha256": "66f212bc73088271dbbec1f3b1c3ba21171e4c5ab38676c4d151441f3e38db6f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-grapheme-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/511a08c03c1960e08a883f4cffcacd219b758354"
                ],
                "cacheFile": "symfony/polyfill-intl-grapheme/3e0defb9f075160deb0ea7188610275ee40a9b00.zip",
                "sha256": "11c409622d2321bfdd2fd1efdbdeaaba95da5211256f6cfdb4e003d7bd7eda45"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-idn-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/639084e360537a19f9ee352433b84ce831f3d2da"
                ],
                "cacheFile": "symfony/polyfill-intl-idn/c8495253150c4daacaf90487f77a76fc7122c16b.zip",
                "sha256": "b2ff6b6408861c6c8c486fcb3bd2109438d5d6ced9175250cfbef1e596665cc4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-normalizer-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/19bd1e4fcd5b91116f14d8533c57831ed00571b6"
                ],
                "cacheFile": "symfony/polyfill-intl-normalizer/3282f96073427a186419bc5ae65aa6726d0f143b.zip",
                "sha256": "22bf30d7b50aabe1846e3ffbc03011903e05f4208d3bb49b373c4e5fe09500b5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-mbstring-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/8ad114f6b39e2c98a8b0e3bd907732c207c2b534"
                ],
                "cacheFile": "symfony/polyfill-mbstring/7061da8bfb2a98acfbdcaf076c3ba5f167d856cc.zip",
                "sha256": "b112101451a1f76a0cb4edd6595a5733059fd2f7a4cd4d36052526602e26a8fa"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php72-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php72/zipball/869329b1e9894268a8a61dabb69153029b7a8c97"
                ],
                "cacheFile": "symfony/polyfill-php72/3dc6f2e0efb0a915be032510852eb9fb9205577c.zip",
                "sha256": "973b3eaa88a3e4d3287b336c4a3e057feca1f9f703f05abd234a07d2105c14c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php80-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php80/zipball/7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936"
                ],
                "cacheFile": "symfony/polyfill-php80/fe4df98f0392f59ca247eec4d07f380451c09242.zip",
                "sha256": "8db38ad9c85c94ad664b89ff9ec9dd5b232dc922f6107bb356d44e9dcf6cde9b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_service-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/service-contracts/zipball/d78d39c1599bd1188b8e26bb341da52c3c6d8a66"
                ],
                "cacheFile": "symfony/service-contracts/880c3cc97a5424e1989454dd2041c0ebdf3dc84e.zip",
                "sha256": "29fd011c3a70250cf370c8a0d774c82e721e636ebba016d860d93bd1bdb0ebb1"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_string-6.0.15.0",
                "urls": [
                    "https://api.github.com/repos/symfony/string/zipball/51ac0fa0ccf132a00519b87c97e8f775fa14e771"
                ],
                "cacheFile": "symfony/string/4f7de1dbdd0c7e670f6974478d519ae8d8e5a602.zip",
                "sha256": "53d506d838113fb82b9ebccc7326188309d234ee1f29be7f9c187e39327b2951"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-6.0.14.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation/zipball/6f99eb179aee4652c0a7cd7c11f2a870d904330c"
                ],
                "cacheFile": "symfony/translation/adf07cd2ec65a8bbfcbb1f40a4e1927969d76c4e.zip",
                "sha256": "b44295327326b8624987f97a47090df275ae6ef18a986f051c7bc9783b74f900"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation-contracts/zipball/acbfbb274e730e5a0236f619b6168d9dedb3e282"
                ],
                "cacheFile": "symfony/translation-contracts/44eea647999ae98fd8a3ebe8f7b3f5c2c3969eeb.zip",
                "sha256": "20e3f9edc8716e64bd7119b11f88c391b07a5550d89cae0064031b358c3489e4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_var-dumper-6.0.14.0",
                "urls": [
                    "https://api.github.com/repos/symfony/var-dumper/zipball/72af925ddd41ca0372d166d004bc38a00c4608cc"
                ],
                "cacheFile": "symfony/var-dumper/53d632060f1f055efc134d7b728b0f6b274f0875.zip",
                "sha256": "84758bc5d048dbdcf8bc4f506df4fcdbdd694d0641f9e917d3a3634bd7f4fc2c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "theseer_tokenizer-1.2.1.0",
                "urls": [
                    "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e"
                ],
                "cacheFile": "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip",
                "sha256": "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "vimeo_psalm-5.4.0.0",
                "urls": [
                    "https://api.github.com/repos/vimeo/psalm/zipball/62db5d4f6a7ae0a20f7cc5a4952d730272fc0863"
                ],
                "cacheFile": "vimeo/psalm/773cbf6daa8f49db6c1488bec2fa0de84047f44c.zip",
                "sha256": "1914382b1eedd050d9b517e0c0f3ca31e2109d7a1316eb858ee9a06935794fa9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "voku_portable-ascii-2.0.1.0",
                "urls": [
                    "https://api.github.com/repos/voku/portable-ascii/zipball/b56450eed252f6801410d810c8e1727224ae0743"
                ],
                "cacheFile": "voku/portable-ascii/d530a9779b65656e504bf4b013e19c70336ba351.zip",
                "sha256": "d45b55bc98e466a41369c4d9a034aa9721a614a7dbde30237299799361d8943f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "webmozart_assert-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/webmozarts/assert/zipball/11cb2199493b2f8a3b53e7f19068fc6aac760991"
                ],
                "cacheFile": "webmozart/assert/b9bc0224905e92da07bc3de7d205f17c30035a88.zip",
                "sha256": "3dea7b980d4ba44fca74fbd1d068be28f1a771e1a1cb308e89b773eb83fa11a3"
            }
        ],
        "projectName": "jbboehr_phpstan-laravel-validation"
    }
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [ ];
  localEntries = data.localEntries or [ ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings
      (args: ''
        (
          cacheFile=${escapeShellArg args.cacheFile}
          cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
          mkdir -p "$(dirname "$cacheFilePath")"
          cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
        )
      '')
      cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings
      (args: ''
        sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
      '')
      localEntries
  );

in
stdenv.mkDerivation {
  name = data.projectName;
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install -n -o

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    # composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
