# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib
, php
, phpPackages
, unzip
, stdenv
, runCommandLocal
, writeText
, fetchurl

  # Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let
  data = builtins.fromJSON ''
        {
        "cacheEntries": [
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nikic_php-parser-4.15.3.0",
                "urls": [
                    "https://api.github.com/repos/nikic/PHP-Parser/zipball/570e980a201d8ed0236b0a62ddf2c9cbb2034039"
                ],
                "cacheFile": "nikic/php-parser/d82d7114a2384784c2ec20cf1dd8fd2ac538f2ba.zip",
                "sha256": "b9d68a41dc37fdb939e2200911ac0610fd37e4169a3171a0eb3a13e5e5b570e0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-1.9.17.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan/zipball/204e459e7822f2c586463029f5ecec31bb45a1f2"
                ],
                "cacheFile": "phpstan/phpstan/9cfa004e0e697525d593fb2914d439a9c4221609.zip",
                "sha256": "b5c7eb2350e91ed1e19dfebbe56d12aad202b951bfc8dfab8a0ee058352a9c76"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "amphp_amp-2.6.2.0",
                "urls": [
                    "https://api.github.com/repos/amphp/amp/zipball/9d5100cebffa729aaffecd3ad25dc5aeea4f13bb"
                ],
                "cacheFile": "amphp/amp/8c9c2a2bf8be8fda4a26bfe6c6e261d39b6b0320.zip",
                "sha256": "c15688dd5756771bb52c1c30f9088327cc49ffb69131183d05b0642e7a4f935f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "amphp_byte-stream-1.8.1.0",
                "urls": [
                    "https://api.github.com/repos/amphp/byte-stream/zipball/acbd8002b3536485c997c4e019206b3f10ca15bd"
                ],
                "cacheFile": "amphp/byte-stream/24823ac0e49e56800f97cb0f4e852334fc3a60e0.zip",
                "sha256": "227fbf5650a188d0e7da15b61642bc2a076ed7cd293f20f92205eff862615892"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "brick_math-0.11.0.0",
                "urls": [
                    "https://api.github.com/repos/brick/math/zipball/0ad82ce168c82ba30d1c01ec86116ab52f589478"
                ],
                "cacheFile": "brick/math/195eda47beececd923d5b93f8a31c834da4db6cd.zip",
                "sha256": "cb93121cd6d55a7c57296c603375320d09f404cbb04a292d1986dc8d61f07812"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "brick_varexporter-0.3.8.0",
                "urls": [
                    "https://api.github.com/repos/brick/varexporter/zipball/b5853edea6204ff8fa10633c3a4cccc4058410ed"
                ],
                "cacheFile": "brick/varexporter/7dcce8a1a2013e24367e88fb9e52154bd7e1a778.zip",
                "sha256": "f5650f7774409e8121b56b968fe67e101883099d8693abada73139f07e22a04c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_package-versions-deprecated-1.11.99.5",
                "urls": [
                    "https://api.github.com/repos/composer/package-versions-deprecated/zipball/b4f54f74ef3453349c24a845d22392cd31e65f1d"
                ],
                "cacheFile": "composer/package-versions-deprecated/7696d631625b248d150b3db3037b6fb36a2f1cf1.zip",
                "sha256": "557187e1f72faff2b2e61fedd93824c74b491f6078c8135fe2978488e6ee32c3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_pcre-3.1.0.0",
                "urls": [
                    "https://api.github.com/repos/composer/pcre/zipball/4bff79ddd77851fe3cdd11616ed3f92841ba5bd2"
                ],
                "cacheFile": "composer/pcre/16ea22f0a3bddd3c7683dfc2378869ab617d3036.zip",
                "sha256": "3aff2a08d578d70c7b1f78553de1962f39a973097dee9bb0e46372358b589b15"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_semver-3.3.2.0",
                "urls": [
                    "https://api.github.com/repos/composer/semver/zipball/3953f23262f2bff1919fc82183ad9acb13ff62c9"
                ],
                "cacheFile": "composer/semver/29fa63f52104d4c4bf687735fbaaf52f0a232c4b.zip",
                "sha256": "baaee53811af1c73fa17da54c1722c888207008eac70d0f239073fb13e24e56a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_xdebug-handler-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/composer/xdebug-handler/zipball/ced299686f41dce890debac69273b47ffe98a40c"
                ],
                "cacheFile": "composer/xdebug-handler/524bae0e78ed4946a977f22dc3ff8629f96dfaf7.zip",
                "sha256": "102c6388c487229bbedce718465f5b6bb125c20a655066ae967fcc6ac4cdd0c2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dnoegel_php-xdg-base-dir-0.1.1.0",
                "urls": [
                    "https://api.github.com/repos/dnoegel/php-xdg-base-dir/zipball/8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd"
                ],
                "cacheFile": "dnoegel/php-xdg-base-dir/b81b493e09050800919750bdd1e829656fc89971.zip",
                "sha256": "d881707cf02a8aa1a1846e0166e0b1704eeacac059f08a7ec48b593e3959c40a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_deprecations-1.0.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/deprecations/zipball/0e2a4f1f8cdfc7a92ec3b01c9334898c806b30de"
                ],
                "cacheFile": "doctrine/deprecations/0b11d410b30a1fca6ad657a01bbf1bf8cb37b15b.zip",
                "sha256": "0948892861e2470c164fb0c45063967417c4b9e527ea4cf2b987030b047061ea"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_inflector-2.0.6.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/inflector/zipball/d9d313a36c872fd6ee06d9a6cbcf713eaa40f024"
                ],
                "cacheFile": "doctrine/inflector/57c027282263baa14000cf3525eb68a5f0795e45.zip",
                "sha256": "12dae3b88886e0adde83b1d7338d2df7480620a0ec5ec8cde15935857b05defc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_instantiator-1.5.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/instantiator/zipball/0a0fa9780f5d4e507415a065172d26a98d02047b"
                ],
                "cacheFile": "doctrine/instantiator/281539f78a082d6b6f518e4643e807bb44376df5.zip",
                "sha256": "b2ac699a2ce6afe19db094650009e81eb0471d8cbfaa7a8bb4825e88e6011b03"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_lexer-2.1.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/lexer/zipball/39ab8fcf5a51ce4b85ca97c7a7d033eb12831124"
                ],
                "cacheFile": "doctrine/lexer/b4234cb7c4536da25e7669362cfb87940f58d05f.zip",
                "sha256": "50bde7a5b68b6ef697044ed6256605a3bf19b106491dcbea5dc569041d9a6aa6"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "drupol_composer-plugin-nixify-9999999-dev",
                "urls": [
                    "https://api.github.com/repos/drupol/composer-plugin-nixify/zipball/fd8faf5b898f5366c9d107eb407360b41a477b8f"
                ],
                "cacheFile": "drupol/composer-plugin-nixify/b520a1e323394de2e25d37bf63b8627c8748b840.zip",
                "sha256": "608a34aa52abc812f29b0834ea1334d6c5792cfd12bac20400156f5199819b0e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "egulias_email-validator-3.2.5.0",
                "urls": [
                    "https://api.github.com/repos/egulias/EmailValidator/zipball/b531a2311709443320c786feb4519cfaf94af796"
                ],
                "cacheFile": "egulias/email-validator/fbd93f281d2a45219617370e886cd79b5143b67b.zip",
                "sha256": "ec59ebdc8df85e80c9a207c38b15fda8a84f38d5a25a2da5f017210b6e6b230c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "felixfbecker_advanced-json-rpc-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/felixfbecker/php-advanced-json-rpc/zipball/b5f37dbff9a8ad360ca341f3240dc1c168b45447"
                ],
                "cacheFile": "felixfbecker/advanced-json-rpc/ee93f6a030a8ec4909ae17405ed90c75f9d0c59c.zip",
                "sha256": "98b15c828413b99ecd0670f91ee25eea5ac9453d5507b2d63711dabf44982490"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "felixfbecker_language-server-protocol-1.5.2.0",
                "urls": [
                    "https://api.github.com/repos/felixfbecker/php-language-server-protocol/zipball/6e82196ffd7c62f7794d778ca52b69feec9f2842"
                ],
                "cacheFile": "felixfbecker/language-server-protocol/bee555c8048b240c2c2f28255fef8f3efc814e2c.zip",
                "sha256": "67502ffec7d734cd69d724ef6dca52f40dc7f23752d021b61e384656a86d343e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fidry_cpu-core-counter-0.4.1.0",
                "urls": [
                    "https://api.github.com/repos/theofidry/cpu-core-counter/zipball/79261cc280aded96d098e1b0e0ba0c4881b432c2"
                ],
                "cacheFile": "fidry/cpu-core-counter/50cd15d7ea524aa7ec47ca26b5e85018cf20893e.zip",
                "sha256": "80f8431805509472afa824d56d19e8b36421febb671dbf1a498de9946e79e437"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fruitcake_php-cors-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/fruitcake/php-cors/zipball/58571acbaa5f9f462c9c77e911700ac66f446d4e"
                ],
                "cacheFile": "fruitcake/php-cors/1de04ebee01b584ebc4c86dacbf172b3bc4ee77a.zip",
                "sha256": "a16a913bc20cbd2a26b114975e324dde53e897f068a4fbb8c33fcd467032b5a3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "guzzlehttp_uri-template-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/guzzle/uri-template/zipball/b945d74a55a25a949158444f09ec0d3c120d69e2"
                ],
                "cacheFile": "guzzlehttp/uri-template/458dd37ed5ec454f8f2a0c65076b0672e09e4e3d.zip",
                "sha256": "0e369c50062d365469c4312eebd57cc5eeb33c0d5e3aae8a4db0a3d844266d0b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_collections-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/collections/zipball/f3ac81877e98c0c096ef403ab4f0c7ed96623c18"
                ],
                "cacheFile": "illuminate/collections/1270e9d26788698f109d034a8c901d3924606282.zip",
                "sha256": "6ea73c0de98e8a1c228154ec132d16c818c13cbfcad09d56c9f40f9e2b8b2917"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_conditionable-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/conditionable/zipball/bea24daa0fa84b7e7b0d5b84f62c71b7e2dc3364"
                ],
                "cacheFile": "illuminate/conditionable/93c561aee09880f236eae3c0c95eb878f0378174.zip",
                "sha256": "73138f78ec6391e39411a5e92a85fc8439625ab0e4754a5c5c1887f46856ee7d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_container-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/container/zipball/1641dda2d0750b68bb1264a3b37ff3973f2e6265"
                ],
                "cacheFile": "illuminate/container/4b66e540cfaeba30f4d8706f101c9f93db4a0354.zip",
                "sha256": "4e7ad6e4afec0a4f4f7ce646ac36b7ec640a121383fb8fe5d6ad49161f3bb947"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_contracts-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/contracts/zipball/44f65d723b13823baa02ff69751a5948bde60c22"
                ],
                "cacheFile": "illuminate/contracts/0eb325420fcd2aea815b29e9c380f0fa62e2a78b.zip",
                "sha256": "42c48ccb4ba09b1ef994b300e017d27b4131dfa8df17998d8413be9ee73c6f64"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_filesystem-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/filesystem/zipball/8168361548b2c5e2e501096cfbadb62a4a526290"
                ],
                "cacheFile": "illuminate/filesystem/c8341df2773fac312bc459d28d4886e1bab09b6e.zip",
                "sha256": "c7dd57ba220e7b56ade5cc3b3a0545bcd8b486cc2b3f139a4323f16f9aef33e1"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_http-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/http/zipball/dc92ce3a3dbc5c363fc5a70b2e5d3d109bc88ce2"
                ],
                "cacheFile": "illuminate/http/1e0bbcbdaced8020c95e98cacf895ed660e3b40c.zip",
                "sha256": "03200896912ace346bb5957dc03098b88e9710fc485744337c1ad44b919ccb83"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_macroable-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/macroable/zipball/e3bfaf6401742a9c6abca61b9b10e998e5b6449a"
                ],
                "cacheFile": "illuminate/macroable/795f18e284aa50b093375bcd385436881c49282f.zip",
                "sha256": "5dd68acf1817fb2f7795c60b5f4aa76c66a174241bef5e92c9a7c799b6e2b463"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_session-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/session/zipball/71972e3e01ef501876d916c02c4d9bff77549e33"
                ],
                "cacheFile": "illuminate/session/f2c8c406b90a9fff9aff3552251f556b92421e1a.zip",
                "sha256": "fedb5b06344fc876129cc3da9526899110b63cef3feb79f2d744be419f2eea34"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_support-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/support/zipball/63dcb4523ccdfc01cdf5be17791f07cc20982a1e"
                ],
                "cacheFile": "illuminate/support/4c31d2a870a3f4b36c886ce5a5d6d7baf5ea976d.zip",
                "sha256": "a3454d92cfe3f350e918c4632b3c8c4f8c8711b37ccdd6c254845e1bf8cfefb8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_translation-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/translation/zipball/cc8c7c94cf199077842829a79c2a02ac9146478e"
                ],
                "cacheFile": "illuminate/translation/42130da856e7da78b12fb5cfc1174462b872dd95.zip",
                "sha256": "38ece95267b420619f3c6d76ab84c63a0f92a0aec40dbfe15a22379b024de03b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "illuminate_validation-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/illuminate/validation/zipball/8cd6d3c0151b614e46f3a2a9f7fb77566b012cb0"
                ],
                "cacheFile": "illuminate/validation/ff911bf0a415f0aec969987e7601035c00944725.zip",
                "sha256": "40b4aa8eba67fc6d7a2afbf337a4a777295685cc911bbb17265b7aa8289e7829"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "monolog_monolog-2.9.1.0",
                "urls": [
                    "https://api.github.com/repos/Seldaek/monolog/zipball/f259e2b15fb95494c83f52d3caad003bbf5ffaa1"
                ],
                "cacheFile": "monolog/monolog/af7bafa3cdde5eef658108caf24489923a658da0.zip",
                "sha256": "62ae7992cb222574556c8f276420097d72d5971113fd611881bab315f2a3e753"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "myclabs_deep-copy-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614"
                ],
                "cacheFile": "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip",
                "sha256": "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nesbot_carbon-2.66.0.0",
                "urls": [
                    "https://api.github.com/repos/briannesbitt/Carbon/zipball/496712849902241f04902033b0441b269effe001"
                ],
                "cacheFile": "nesbot/carbon/8a5075a6ddae43266cd352e4dcc76e38a5f9673b.zip",
                "sha256": "1dece0c0233d97157105f55fa02faf1e0a138c6a4368bf0e97dea128195041af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "netresearch_jsonmapper-4.1.0.0",
                "urls": [
                    "https://api.github.com/repos/cweiske/jsonmapper/zipball/cfa81ea1d35294d64adb9c68aa4cb9e92400e53f"
                ],
                "cacheFile": "netresearch/jsonmapper/d2d7958f1c477df80307bcdeee9e2301dfdca0d9.zip",
                "sha256": "1f2c48574155a7c23b6b2735fb8e2cb4480dbed6bc990cb1c27ad2638dc29ec2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_manifest-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53"
                ],
                "cacheFile": "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip",
                "sha256": "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_version-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74"
                ],
                "cacheFile": "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip",
                "sha256": "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_reflection-common-2.2.0.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/ReflectionCommon/zipball/1d01c49d4ed62f25aa84a747ad35d5a16924662b"
                ],
                "cacheFile": "phpdocumentor/reflection-common/6243ab17e2330fb7ce63d34391d53104cc913dc0.zip",
                "sha256": "39fca6dc8730bdc4f70c41e58e16595fc6695b4ae42327c32144c4131410a7f3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_reflection-docblock-5.3.0.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/ReflectionDocBlock/zipball/622548b623e81ca6d78b721c5e029f4ce664f170"
                ],
                "cacheFile": "phpdocumentor/reflection-docblock/3c16e706c93df7017840bcf302eace70dc66a077.zip",
                "sha256": "3664230b09277d49780b0cb8f0a4a324e061f4bad079ac015b49a3892f7440ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_type-resolver-1.6.2.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/TypeResolver/zipball/48f445a408c131e38cab1c235aa6d2bb7a0bb20d"
                ],
                "cacheFile": "phpdocumentor/type-resolver/96bd30e4a669e3eb8e7ff86ae5bd2289737026e6.zip",
                "sha256": "cdaa0d67bc01ab4aeb3361a424e6cd716ef229422b63b4f7b425a6afba4de1f9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-php-parser-1.1.0.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-php-parser/zipball/1c7670dd92da864b5d019f22d9f512a6ae18b78e"
                ],
                "cacheFile": "phpstan/phpstan-php-parser/3a60f66030b521425d4ae82eb36a348495b6c779.zip",
                "sha256": "7905d6a8cef6fa2896ff7ce86ec9118addafb9a6e282553bd32957fb6de7bf85"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-phpunit-1.3.4.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-phpunit/zipball/d77af96c1aaec28f7c0293677132eaaad079e01b"
                ],
                "cacheFile": "phpstan/phpstan-phpunit/094e089a621e8a8f735c95f3823e0ca5a1fc0d47.zip",
                "sha256": "4616659fcef11c89f6c7dfd7011b382624e816ec3287e0213c23cd5c2623af0f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-strict-rules-1.4.5.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-strict-rules/zipball/361f75b06066f3fdaba87c1f57bdb1ffc28d6f1d"
                ],
                "cacheFile": "phpstan/phpstan-strict-rules/a61fa77a7a0b3524e0a2ea685491e897818d534b.zip",
                "sha256": "506bc225e063b457682b0b4742ff5bc0900201702dd963ea731e06b1bd001eea"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-code-coverage-9.2.24.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/2cf940ebc6355a9d430462811b5aaa308b174bed"
                ],
                "cacheFile": "phpunit/php-code-coverage/22950ed3ec19594703b2c51ce0c35f7e8c502d87.zip",
                "sha256": "ea8717edadc67bd1817b2d4a79cedc7e5540b0ff3ae984655df32dc6b13bb2d2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-file-iterator-3.0.6.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf"
                ],
                "cacheFile": "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip",
                "sha256": "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-invoker-3.1.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67"
                ],
                "cacheFile": "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip",
                "sha256": "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-text-template-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28"
                ],
                "cacheFile": "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip",
                "sha256": "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-timer-5.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2"
                ],
                "cacheFile": "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip",
                "sha256": "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_phpunit-9.6.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/e7b1615e3e887d6c719121c6d4a44b0ab9645555"
                ],
                "cacheFile": "phpunit/phpunit/43638934ebf3cb1d505efcd402ac91eee55732e5.zip",
                "sha256": "7a248a5f760d15264e4cc3b116b5234c9fb5b6f8d9a22c470e5c61d5e97eebdc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_container-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
                ],
                "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
                "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_event-dispatcher-1.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/event-dispatcher/zipball/dbefd12671e8a14ec7f180cab83036ed26714bb0"
                ],
                "cacheFile": "psr/event-dispatcher/8f60a8cd1b7ff4e8f9782d70d78dee877a526529.zip",
                "sha256": "4d6a674cfd89a9957ead82e31ee4df785b2b1d215693add73184729a9a66d116"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_log-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001"
                ],
                "cacheFile": "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip",
                "sha256": "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_simple-cache-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/simple-cache/zipball/764e0b3939f5ca87cb904f570ef9be2d78a07865"
                ],
                "cacheFile": "psr/simple-cache/f30344b376a5fb0289c0491e8df6aba973ba12aa.zip",
                "sha256": "e899e363a85c26b3f1a621182b6eed2a37a71d823410ac949a1cbfd4b655ec41"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_cli-parser-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2"
                ],
                "cacheFile": "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip",
                "sha256": "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-1.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120"
                ],
                "cacheFile": "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip",
                "sha256": "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-reverse-lookup-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5"
                ],
                "cacheFile": "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip",
                "sha256": "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_comparator-4.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a"
                ],
                "cacheFile": "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip",
                "sha256": "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_complexity-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88"
                ],
                "cacheFile": "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip",
                "sha256": "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_diff-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d"
                ],
                "cacheFile": "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip",
                "sha256": "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_environment-5.1.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/environment/zipball/830c43a844f1f8d5b7a1f6d6076b784454d8b7ed"
                ],
                "cacheFile": "sebastian/environment/2233d3b38ac6d485959f6c153c851f07547fee65.zip",
                "sha256": "f653465ac3278f2109df985a8cfab6bb8a0524f4f0861d4e993f001b872d0408"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_exporter-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d"
                ],
                "cacheFile": "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip",
                "sha256": "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_global-state-5.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2"
                ],
                "cacheFile": "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip",
                "sha256": "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_lines-of-code-1.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc"
                ],
                "cacheFile": "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip",
                "sha256": "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-enumerator-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71"
                ],
                "cacheFile": "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip",
                "sha256": "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-reflector-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7"
                ],
                "cacheFile": "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip",
                "sha256": "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_recursion-context-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1"
                ],
                "cacheFile": "sebastian/recursion-context/4b7cea85c6a1d0a92ff75035f6b0545625890a5f.zip",
                "sha256": "8102972caec5c2041cb1b156913ac9a320cca9943dc94cde79be43e7baf6e6a9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_resource-operations-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8"
                ],
                "cacheFile": "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip",
                "sha256": "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_type-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/type/zipball/75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7"
                ],
                "cacheFile": "sebastian/type/6c52c952769f461058a7bcc9db2baadd3633dfc8.zip",
                "sha256": "8507e504e5e67b8ac937a96373d980464fd8c1fa7211dd3f14fe2e2cccda6e2f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_version-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c"
                ],
                "cacheFile": "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip",
                "sha256": "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_array-to-xml-2.17.1.0",
                "urls": [
                    "https://api.github.com/repos/spatie/array-to-xml/zipball/5cbec9c6ab17e320c58a259f0cebe88bde4a7c46"
                ],
                "cacheFile": "spatie/array-to-xml/2d0ab160be3e2ff234108c2f17ad6a074bc4116b.zip",
                "sha256": "a6fd5a96dfad96c685f963e55debd71959b27fd2f82071b91e03d724442a010c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "squizlabs_php_codesniffer-3.7.1.0",
                "urls": [
                    "https://api.github.com/repos/squizlabs/PHP_CodeSniffer/zipball/1359e176e9307e906dc3d890bcc9603ff6d90619"
                ],
                "cacheFile": "squizlabs/php_codesniffer/87828c804599927aa873e78e73b71ea8ed2dc48e.zip",
                "sha256": "41d8bad949966238289179ca65792e9b119fcf650a0e1a1dd7e0f51cbf00eb2d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_console-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/console/zipball/c3ebc83d031b71c39da318ca8b7a07ecc67507ed"
                ],
                "cacheFile": "symfony/console/cf1079e94604413572fdb9c8077dac3dca76a928.zip",
                "sha256": "d786f534c0ae5b1d621b2e5ac30c87145803e2d53a8252113aa923f09ce06def"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_deprecation-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/deprecation-contracts/zipball/26954b3d62a6c5fd0ea8a2a00c0353a14978d05c"
                ],
                "cacheFile": "symfony/deprecation-contracts/4d47eca6ee854e21b5f9e5f3b411189f019bd558.zip",
                "sha256": "b70da9d9324b76f55b2ef8afbb11f45c3b59353dcecb27527e55faf56c928af2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_error-handler-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/error-handler/zipball/c7df52182f43a68522756ac31a532dd5b1e6db67"
                ],
                "cacheFile": "symfony/error-handler/4362d8dc8940e32a8626557fd58d2710814db8a8.zip",
                "sha256": "889ded73433e7b5b6d6883d7f2fc14cbc7f9f30dffa27eb049b37ec3870519b7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher/zipball/2eaf8e63bc5b8cefabd4a800157f0d0c094f677a"
                ],
                "cacheFile": "symfony/event-dispatcher/a750d7e7582528dfc9f4323bc9db63e44636ca0e.zip",
                "sha256": "567bf06bb91ab50220e74d2d66bd80fd07ba21c673c0461f17a0d82060879773"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher-contracts/zipball/7bc61cc2db649b4637d331240c5346dcc7708051"
                ],
                "cacheFile": "symfony/event-dispatcher-contracts/209216ef5d7de22ca666c1d9ae275b3a79137b63.zip",
                "sha256": "91f051a5b67196f07ca500d5b75769cedf9fb24a219dc91d01c9caf288143db3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_filesystem-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/filesystem/zipball/3d49eec03fda1f0fc19b7349fbbe55ebc1004214"
                ],
                "cacheFile": "symfony/filesystem/b192242a5e1939b8aa4a63b9b6ea99ccb9b5feed.zip",
                "sha256": "deafa5bd6ae0f7479bd02127567a8a095934fe25b003567e2ac3d8548df41636"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_finder-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/finder/zipball/5cc9cac6586fc0c28cd173780ca696e419fefa11"
                ],
                "cacheFile": "symfony/finder/817d215ed4fd7554a45f2763e8517638d731b938.zip",
                "sha256": "ac898e03564ce34448dc7b4d6ecf7372e6f61dd4593036c0ea3f33fe595f1ab8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-foundation-6.0.20.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-foundation/zipball/e16b2676a4b3b1fa12378a20b29c364feda2a8d6"
                ],
                "cacheFile": "symfony/http-foundation/45a020b64d79b7780487503081036f1e9c4e436d.zip",
                "sha256": "4f908b221915c63d4cc65eb64ec3ece19aacdd9de2d140913c589fd8d97f4e34"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-kernel-6.0.20.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-kernel/zipball/6dc70833fd0ef5e861e17c7854c12d7d86679349"
                ],
                "cacheFile": "symfony/http-kernel/6a1c18a8a9008a05ad1e8d8ac14e562b677c4d3e.zip",
                "sha256": "59480623f65632124f8a9ddb9e1999416294fc790193f0243f5d5bf242483fc8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_mime-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/mime/zipball/d7052547a0070cbeadd474e172b527a00d657301"
                ],
                "cacheFile": "symfony/mime/97dd79548f9a68459d2c0b3801017bb73992c73e.zip",
                "sha256": "8a09b1fd03b9b95a6352692798f3b06674192509d0cfb0311617d9c62e73b200"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-ctype-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a"
                ],
                "cacheFile": "symfony/polyfill-ctype/04e84c03a82a82c09eaa688b17b523570f9d14d2.zip",
                "sha256": "66f212bc73088271dbbec1f3b1c3ba21171e4c5ab38676c4d151441f3e38db6f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-grapheme-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/511a08c03c1960e08a883f4cffcacd219b758354"
                ],
                "cacheFile": "symfony/polyfill-intl-grapheme/3e0defb9f075160deb0ea7188610275ee40a9b00.zip",
                "sha256": "11c409622d2321bfdd2fd1efdbdeaaba95da5211256f6cfdb4e003d7bd7eda45"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-idn-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/639084e360537a19f9ee352433b84ce831f3d2da"
                ],
                "cacheFile": "symfony/polyfill-intl-idn/c8495253150c4daacaf90487f77a76fc7122c16b.zip",
                "sha256": "b2ff6b6408861c6c8c486fcb3bd2109438d5d6ced9175250cfbef1e596665cc4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-normalizer-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/19bd1e4fcd5b91116f14d8533c57831ed00571b6"
                ],
                "cacheFile": "symfony/polyfill-intl-normalizer/3282f96073427a186419bc5ae65aa6726d0f143b.zip",
                "sha256": "22bf30d7b50aabe1846e3ffbc03011903e05f4208d3bb49b373c4e5fe09500b5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-mbstring-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/8ad114f6b39e2c98a8b0e3bd907732c207c2b534"
                ],
                "cacheFile": "symfony/polyfill-mbstring/7061da8bfb2a98acfbdcaf076c3ba5f167d856cc.zip",
                "sha256": "b112101451a1f76a0cb4edd6595a5733059fd2f7a4cd4d36052526602e26a8fa"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php72-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php72/zipball/869329b1e9894268a8a61dabb69153029b7a8c97"
                ],
                "cacheFile": "symfony/polyfill-php72/3dc6f2e0efb0a915be032510852eb9fb9205577c.zip",
                "sha256": "973b3eaa88a3e4d3287b336c4a3e057feca1f9f703f05abd234a07d2105c14c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php80-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php80/zipball/7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936"
                ],
                "cacheFile": "symfony/polyfill-php80/fe4df98f0392f59ca247eec4d07f380451c09242.zip",
                "sha256": "8db38ad9c85c94ad664b89ff9ec9dd5b232dc922f6107bb356d44e9dcf6cde9b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_service-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/service-contracts/zipball/d78d39c1599bd1188b8e26bb341da52c3c6d8a66"
                ],
                "cacheFile": "symfony/service-contracts/880c3cc97a5424e1989454dd2041c0ebdf3dc84e.zip",
                "sha256": "29fd011c3a70250cf370c8a0d774c82e721e636ebba016d860d93bd1bdb0ebb1"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_string-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/string/zipball/d9e72497367c23e08bf94176d2be45b00a9d232a"
                ],
                "cacheFile": "symfony/string/e796042fe8f8b82e77830831c7c6d53392aef0ef.zip",
                "sha256": "ee429a33627423a81f054759a7d1683b026b1ab299e0ff50b44ddce624db9b4c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation/zipball/9c24b3fdbbe9fb2ef3a6afd8bbaadfd72dad681f"
                ],
                "cacheFile": "symfony/translation/c54c98fab1ed0ac0cbe6903e9903620c372e606c.zip",
                "sha256": "a2139db9ba1292d47e2d6266838087c7d00af69d1389dbd133003249cb1c8189"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-contracts-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation-contracts/zipball/acbfbb274e730e5a0236f619b6168d9dedb3e282"
                ],
                "cacheFile": "symfony/translation-contracts/44eea647999ae98fd8a3ebe8f7b3f5c2c3969eeb.zip",
                "sha256": "20e3f9edc8716e64bd7119b11f88c391b07a5550d89cae0064031b358c3489e4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_var-dumper-6.0.19.0",
                "urls": [
                    "https://api.github.com/repos/symfony/var-dumper/zipball/eb980457fa6899840fe1687e8627a03a7d8a3d52"
                ],
                "cacheFile": "symfony/var-dumper/90b70e68fa941316917bae41e2d65a393682df40.zip",
                "sha256": "53b02741e18dfc79c9b2f8f5e037ad0189c55379f7ab837d97749213897e71a0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "theseer_tokenizer-1.2.1.0",
                "urls": [
                    "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e"
                ],
                "cacheFile": "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip",
                "sha256": "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "vimeo_psalm-5.6.0.0",
                "urls": [
                    "https://api.github.com/repos/vimeo/psalm/zipball/e784128902dfe01d489c4123d69918a9f3c1eac5"
                ],
                "cacheFile": "vimeo/psalm/cc6eb1638a99e71b38c90a484071cc0d9d557f25.zip",
                "sha256": "c476ca6edad1cc54238b322442f730fea95e88ee917410e645001e5c8b57e728"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "voku_portable-ascii-2.0.1.0",
                "urls": [
                    "https://api.github.com/repos/voku/portable-ascii/zipball/b56450eed252f6801410d810c8e1727224ae0743"
                ],
                "cacheFile": "voku/portable-ascii/d530a9779b65656e504bf4b013e19c70336ba351.zip",
                "sha256": "d45b55bc98e466a41369c4d9a034aa9721a614a7dbde30237299799361d8943f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "webmozart_assert-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/webmozarts/assert/zipball/11cb2199493b2f8a3b53e7f19068fc6aac760991"
                ],
                "cacheFile": "webmozart/assert/b9bc0224905e92da07bc3de7d205f17c30035a88.zip",
                "sha256": "3dea7b980d4ba44fca74fbd1d068be28f1a771e1a1cb308e89b773eb83fa11a3"
            }
        ],
        "projectName": "jbboehr_phpstan-laravel-validation"
    }
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [ ];
  localEntries = data.localEntries or [ ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings
      (args: ''
        (
          cacheFile=${escapeShellArg args.cacheFile}
          cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
          mkdir -p "$(dirname "$cacheFilePath")"
          cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
        )
      '')
      cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings
      (args: ''
        sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
      '')
      localEntries
  );

in
stdenv.mkDerivation {
  name = data.projectName;
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install -n -o

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    # composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
