# This file is generated by composer-plugin-nixify.
# Manual changes might be lost - proceed with caution!

{ lib
, php
, phpPackages
, unzip
, stdenv
, runCommandLocal
, writeText
, fetchurl

  # Default fetcher.
, fetcher ? (args: fetchurl { inherit (args) name urls sha256; })

}: src:

with lib;

let
  data = builtins.fromJSON ''
        {
        "cacheEntries": [
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nikic_php-parser-4.15.3.0",
                "urls": [
                    "https://api.github.com/repos/nikic/PHP-Parser/zipball/570e980a201d8ed0236b0a62ddf2c9cbb2034039"
                ],
                "cacheFile": "nikic/php-parser/d82d7114a2384784c2ec20cf1dd8fd2ac538f2ba.zip",
                "sha256": "b9d68a41dc37fdb939e2200911ac0610fd37e4169a3171a0eb3a13e5e5b570e0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-1.9.17.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan/zipball/204e459e7822f2c586463029f5ecec31bb45a1f2"
                ],
                "cacheFile": "phpstan/phpstan/9cfa004e0e697525d593fb2914d439a9c4221609.zip",
                "sha256": "b5c7eb2350e91ed1e19dfebbe56d12aad202b951bfc8dfab8a0ee058352a9c76"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "amphp_amp-2.6.2.0",
                "urls": [
                    "https://api.github.com/repos/amphp/amp/zipball/9d5100cebffa729aaffecd3ad25dc5aeea4f13bb"
                ],
                "cacheFile": "amphp/amp/8c9c2a2bf8be8fda4a26bfe6c6e261d39b6b0320.zip",
                "sha256": "c15688dd5756771bb52c1c30f9088327cc49ffb69131183d05b0642e7a4f935f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "amphp_byte-stream-1.8.1.0",
                "urls": [
                    "https://api.github.com/repos/amphp/byte-stream/zipball/acbd8002b3536485c997c4e019206b3f10ca15bd"
                ],
                "cacheFile": "amphp/byte-stream/24823ac0e49e56800f97cb0f4e852334fc3a60e0.zip",
                "sha256": "227fbf5650a188d0e7da15b61642bc2a076ed7cd293f20f92205eff862615892"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "brick_math-0.10.2.0",
                "urls": [
                    "https://api.github.com/repos/brick/math/zipball/459f2781e1a08d52ee56b0b1444086e038561e3f"
                ],
                "cacheFile": "brick/math/fc3801b79995ca2750189dd15609bb81d3cabbca.zip",
                "sha256": "77113779640ced089eb8a7e2475e925d5c7b48fcf129f921051666ee878f0f03"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "brick_varexporter-0.3.8.0",
                "urls": [
                    "https://api.github.com/repos/brick/varexporter/zipball/b5853edea6204ff8fa10633c3a4cccc4058410ed"
                ],
                "cacheFile": "brick/varexporter/7dcce8a1a2013e24367e88fb9e52154bd7e1a778.zip",
                "sha256": "f5650f7774409e8121b56b968fe67e101883099d8693abada73139f07e22a04c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_package-versions-deprecated-1.11.99.5",
                "urls": [
                    "https://api.github.com/repos/composer/package-versions-deprecated/zipball/b4f54f74ef3453349c24a845d22392cd31e65f1d"
                ],
                "cacheFile": "composer/package-versions-deprecated/7696d631625b248d150b3db3037b6fb36a2f1cf1.zip",
                "sha256": "557187e1f72faff2b2e61fedd93824c74b491f6078c8135fe2978488e6ee32c3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_pcre-3.1.0.0",
                "urls": [
                    "https://api.github.com/repos/composer/pcre/zipball/4bff79ddd77851fe3cdd11616ed3f92841ba5bd2"
                ],
                "cacheFile": "composer/pcre/16ea22f0a3bddd3c7683dfc2378869ab617d3036.zip",
                "sha256": "3aff2a08d578d70c7b1f78553de1962f39a973097dee9bb0e46372358b589b15"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_semver-3.3.2.0",
                "urls": [
                    "https://api.github.com/repos/composer/semver/zipball/3953f23262f2bff1919fc82183ad9acb13ff62c9"
                ],
                "cacheFile": "composer/semver/29fa63f52104d4c4bf687735fbaaf52f0a232c4b.zip",
                "sha256": "baaee53811af1c73fa17da54c1722c888207008eac70d0f239073fb13e24e56a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "composer_xdebug-handler-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/composer/xdebug-handler/zipball/ced299686f41dce890debac69273b47ffe98a40c"
                ],
                "cacheFile": "composer/xdebug-handler/524bae0e78ed4946a977f22dc3ff8629f96dfaf7.zip",
                "sha256": "102c6388c487229bbedce718465f5b6bb125c20a655066ae967fcc6ac4cdd0c2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dflydev_dot-access-data-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/dflydev/dflydev-dot-access-data/zipball/f41715465d65213d644d3141a6a93081be5d3549"
                ],
                "cacheFile": "dflydev/dot-access-data/5872417a18bbb69b106dc09a3b09c46b193e0110.zip",
                "sha256": "b2ae92836d920d2a968b32acd80e1c39a1446c749ddae28dc806408c7096ebed"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dnoegel_php-xdg-base-dir-0.1.1.0",
                "urls": [
                    "https://api.github.com/repos/dnoegel/php-xdg-base-dir/zipball/8f8a6e48c5ecb0f991c2fdcf5f154a47d85f9ffd"
                ],
                "cacheFile": "dnoegel/php-xdg-base-dir/b81b493e09050800919750bdd1e829656fc89971.zip",
                "sha256": "d881707cf02a8aa1a1846e0166e0b1704eeacac059f08a7ec48b593e3959c40a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_inflector-2.0.6.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/inflector/zipball/d9d313a36c872fd6ee06d9a6cbcf713eaa40f024"
                ],
                "cacheFile": "doctrine/inflector/57c027282263baa14000cf3525eb68a5f0795e45.zip",
                "sha256": "12dae3b88886e0adde83b1d7338d2df7480620a0ec5ec8cde15935857b05defc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_instantiator-2.0.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/instantiator/zipball/c6222283fa3f4ac679f8b9ced9a4e23f163e80d0"
                ],
                "cacheFile": "doctrine/instantiator/48cd70ce44111f1be53796d18d263cd47da09a3f.zip",
                "sha256": "966dccf8ebce17e2883e59d65c4172a3c4008d2c0039421523a2823f0e872a15"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "doctrine_lexer-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/doctrine/lexer/zipball/84a527db05647743d50373e0ec53a152f2cde568"
                ],
                "cacheFile": "doctrine/lexer/799bfa3c0767416b458bd3c44a9911a170407677.zip",
                "sha256": "e07c83d6c4e96f758a3adc17388a19934f2f64ebbc363381fd180e2c37bac3f2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "dragonmantank_cron-expression-3.3.2.0",
                "urls": [
                    "https://api.github.com/repos/dragonmantank/cron-expression/zipball/782ca5968ab8b954773518e9e49a6f892a34b2a8"
                ],
                "cacheFile": "dragonmantank/cron-expression/4f2cae11a28f521a6bbb27396bf433acc336909b.zip",
                "sha256": "e961b1c2dcc99c0b1a34f4501833cb0941208ae5e40ae1e7e7d08b3576b0fda2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "drupol_composer-plugin-nixify-9999999-dev",
                "urls": [
                    "https://api.github.com/repos/drupol/composer-plugin-nixify/zipball/fd8faf5b898f5366c9d107eb407360b41a477b8f"
                ],
                "cacheFile": "drupol/composer-plugin-nixify/b520a1e323394de2e25d37bf63b8627c8748b840.zip",
                "sha256": "608a34aa52abc812f29b0834ea1334d6c5792cfd12bac20400156f5199819b0e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "egulias_email-validator-4.0.1.0",
                "urls": [
                    "https://api.github.com/repos/egulias/EmailValidator/zipball/3a85486b709bc384dae8eb78fb2eec649bdb64ff"
                ],
                "cacheFile": "egulias/email-validator/f2b96d737edce903bd0aa35aa9afc48c74fffe35.zip",
                "sha256": "bcaf356b0877d68b858783646c4bbf9fcb569c9aff36e0dd052199f71c697ced"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "felixfbecker_advanced-json-rpc-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/felixfbecker/php-advanced-json-rpc/zipball/b5f37dbff9a8ad360ca341f3240dc1c168b45447"
                ],
                "cacheFile": "felixfbecker/advanced-json-rpc/ee93f6a030a8ec4909ae17405ed90c75f9d0c59c.zip",
                "sha256": "98b15c828413b99ecd0670f91ee25eea5ac9453d5507b2d63711dabf44982490"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "felixfbecker_language-server-protocol-1.5.2.0",
                "urls": [
                    "https://api.github.com/repos/felixfbecker/php-language-server-protocol/zipball/6e82196ffd7c62f7794d778ca52b69feec9f2842"
                ],
                "cacheFile": "felixfbecker/language-server-protocol/bee555c8048b240c2c2f28255fef8f3efc814e2c.zip",
                "sha256": "67502ffec7d734cd69d724ef6dca52f40dc7f23752d021b61e384656a86d343e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fidry_cpu-core-counter-0.4.1.0",
                "urls": [
                    "https://api.github.com/repos/theofidry/cpu-core-counter/zipball/79261cc280aded96d098e1b0e0ba0c4881b432c2"
                ],
                "cacheFile": "fidry/cpu-core-counter/50cd15d7ea524aa7ec47ca26b5e85018cf20893e.zip",
                "sha256": "80f8431805509472afa824d56d19e8b36421febb671dbf1a498de9946e79e437"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "fruitcake_php-cors-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/fruitcake/php-cors/zipball/58571acbaa5f9f462c9c77e911700ac66f446d4e"
                ],
                "cacheFile": "fruitcake/php-cors/1de04ebee01b584ebc4c86dacbf172b3bc4ee77a.zip",
                "sha256": "a16a913bc20cbd2a26b114975e324dde53e897f068a4fbb8c33fcd467032b5a3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "graham-campbell_result-type-1.1.0.0",
                "urls": [
                    "https://api.github.com/repos/GrahamCampbell/Result-Type/zipball/a878d45c1914464426dc94da61c9e1d36ae262a8"
                ],
                "cacheFile": "graham-campbell/result-type/7fcdb89c98fdc16e9029a7634abb83d2a6e18464.zip",
                "sha256": "6b8717820fc9b49de9d9adb9cbccd1c35ffd9a3f341d767bf4c7902592565ef5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "guzzlehttp_uri-template-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/guzzle/uri-template/zipball/b945d74a55a25a949158444f09ec0d3c120d69e2"
                ],
                "cacheFile": "guzzlehttp/uri-template/458dd37ed5ec454f8f2a0c65076b0672e09e4e3d.zip",
                "sha256": "0e369c50062d365469c4312eebd57cc5eeb33c0d5e3aae8a4db0a3d844266d0b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "laravel_framework-9.52.0.0",
                "urls": [
                    "https://api.github.com/repos/laravel/framework/zipball/eb85cd9d72e5bfa54b4d0d9040786f26d6184a9e"
                ],
                "cacheFile": "laravel/framework/1faf5ada09af4a224cd81bf4be17966eb133c579.zip",
                "sha256": "925da285d508e445965000e2be89b0496bae25ead8d23a96eb119c9660024a39"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "laravel_serializable-closure-1.3.0.0",
                "urls": [
                    "https://api.github.com/repos/laravel/serializable-closure/zipball/f23fe9d4e95255dacee1bf3525e0810d1a1b0f37"
                ],
                "cacheFile": "laravel/serializable-closure/728814a9e03933b6eed6a78910a61878db473045.zip",
                "sha256": "b4a13fa026d52a40e069eb16158536f2e3f8670f8ba867e8338b065ce0c5db37"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_commonmark-2.3.9.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/commonmark/zipball/c1e114f74e518daca2729ea8c4bf1167038fa4b5"
                ],
                "cacheFile": "league/commonmark/18a5b18d8401ee1531486703e06eb3cca51bc192.zip",
                "sha256": "07c11e20f0ad729895e43bf3dc7e67e1c47e1bd2231e06ed135233877c666481"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_config-1.2.0.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/config/zipball/754b3604fb2984c71f4af4a9cbe7b57f346ec1f3"
                ],
                "cacheFile": "league/config/63acc0c0da84dd8710b3a4e58a6a4e393530da19.zip",
                "sha256": "1ad93a2858d4479e29d29b88d0d3e4ac4221631b06959454ae4061d058414b7a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_flysystem-3.12.2.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/flysystem/zipball/f6377c709d2275ed6feaf63e44be7a7162b0e77f"
                ],
                "cacheFile": "league/flysystem/e9a3840718adf9cea0aefabeedff286672a14977.zip",
                "sha256": "a5de3dfe00551c7e471f2f01a52aa8ce5fe0d91b1456029991c9ca9ad9847839"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "league_mime-type-detection-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/thephpleague/mime-type-detection/zipball/ff6248ea87a9f116e78edd6002e39e5128a0d4dd"
                ],
                "cacheFile": "league/mime-type-detection/f9602cfc5f45723d4f590e49e3683471bec330cb.zip",
                "sha256": "dfed2ddf02aee15b220396813b02e48e0d662cd772233f26dbe333d3f0b6c3a8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "monolog_monolog-2.9.1.0",
                "urls": [
                    "https://api.github.com/repos/Seldaek/monolog/zipball/f259e2b15fb95494c83f52d3caad003bbf5ffaa1"
                ],
                "cacheFile": "monolog/monolog/af7bafa3cdde5eef658108caf24489923a658da0.zip",
                "sha256": "62ae7992cb222574556c8f276420097d72d5971113fd611881bab315f2a3e753"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "myclabs_deep-copy-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/myclabs/DeepCopy/zipball/14daed4296fae74d9e3201d2c4925d1acb7aa614"
                ],
                "cacheFile": "myclabs/deep-copy/8a47e905abc875fa8049c320097a46a9c305b50b.zip",
                "sha256": "3c357c9554caa4d6d71117ce8cfb7db23c1ac64eb28a1e659988cbcf201ba984"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nesbot_carbon-2.66.0.0",
                "urls": [
                    "https://api.github.com/repos/briannesbitt/Carbon/zipball/496712849902241f04902033b0441b269effe001"
                ],
                "cacheFile": "nesbot/carbon/8a5075a6ddae43266cd352e4dcc76e38a5f9673b.zip",
                "sha256": "1dece0c0233d97157105f55fa02faf1e0a138c6a4368bf0e97dea128195041af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "netresearch_jsonmapper-4.1.0.0",
                "urls": [
                    "https://api.github.com/repos/cweiske/jsonmapper/zipball/cfa81ea1d35294d64adb9c68aa4cb9e92400e53f"
                ],
                "cacheFile": "netresearch/jsonmapper/d2d7958f1c477df80307bcdeee9e2301dfdca0d9.zip",
                "sha256": "1f2c48574155a7c23b6b2735fb8e2cb4480dbed6bc990cb1c27ad2638dc29ec2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nette_schema-1.2.3.0",
                "urls": [
                    "https://api.github.com/repos/nette/schema/zipball/abbdbb70e0245d5f3bf77874cea1dfb0c930d06f"
                ],
                "cacheFile": "nette/schema/34af605f2e76f1123861e91e0fa1dae2bf859457.zip",
                "sha256": "b840b5cf98b9a7bd6edc3f34fdeef688106127e2ca917b015eb55e096a7c289a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nette_utils-4.0.0.0",
                "urls": [
                    "https://api.github.com/repos/nette/utils/zipball/cacdbf5a91a657ede665c541eda28941d4b09c1e"
                ],
                "cacheFile": "nette/utils/c420a850090625206da0b557fd85d53ede5655b4.zip",
                "sha256": "10d5131bf50b98dbf4d591d0223c931a3cf48e43c15382493b32e5da7ad16a6c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "nunomaduro_termwind-1.15.1.0",
                "urls": [
                    "https://api.github.com/repos/nunomaduro/termwind/zipball/8ab0b32c8caa4a2e09700ea32925441385e4a5dc"
                ],
                "cacheFile": "nunomaduro/termwind/639200e9d07a30deac047f3f6a96c3738f7c49e1.zip",
                "sha256": "87da562a3e28fd7c23da12b61927d561a888d04247ee659a2f9a0470f0dde5bc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_manifest-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/manifest/zipball/97803eca37d319dfa7826cc2437fc020857acb53"
                ],
                "cacheFile": "phar-io/manifest/99001d1a4fa9041c56147e32147fb55de1cf9383.zip",
                "sha256": "3cb072c02dc066ff22531c8bb5bdf1a4e1dca6207c378218f75c4f4680d4ed80"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phar-io_version-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/phar-io/version/zipball/4f7fd7836c6f332bb2933569e566a0d6c4cbed74"
                ],
                "cacheFile": "phar-io/version/1495d1d88b1ae7e031b437037ce96298d897a969.zip",
                "sha256": "4f6f4fab8bfeac95934cec75be23743e38b6d864876f52dcdd5b54e003fcab55"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_reflection-common-2.2.0.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/ReflectionCommon/zipball/1d01c49d4ed62f25aa84a747ad35d5a16924662b"
                ],
                "cacheFile": "phpdocumentor/reflection-common/6243ab17e2330fb7ce63d34391d53104cc913dc0.zip",
                "sha256": "39fca6dc8730bdc4f70c41e58e16595fc6695b4ae42327c32144c4131410a7f3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_reflection-docblock-5.3.0.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/ReflectionDocBlock/zipball/622548b623e81ca6d78b721c5e029f4ce664f170"
                ],
                "cacheFile": "phpdocumentor/reflection-docblock/3c16e706c93df7017840bcf302eace70dc66a077.zip",
                "sha256": "3664230b09277d49780b0cb8f0a4a324e061f4bad079ac015b49a3892f7440ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpdocumentor_type-resolver-1.6.2.0",
                "urls": [
                    "https://api.github.com/repos/phpDocumentor/TypeResolver/zipball/48f445a408c131e38cab1c235aa6d2bb7a0bb20d"
                ],
                "cacheFile": "phpdocumentor/type-resolver/96bd30e4a669e3eb8e7ff86ae5bd2289737026e6.zip",
                "sha256": "cdaa0d67bc01ab4aeb3361a424e6cd716ef229422b63b4f7b425a6afba4de1f9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpoption_phpoption-1.9.0.0",
                "urls": [
                    "https://api.github.com/repos/schmittjoh/php-option/zipball/dc5ff11e274a90cc1c743f66c9ad700ce50db9ab"
                ],
                "cacheFile": "phpoption/phpoption/bba71c7f765409778b1f6d984ec2a76bf6c28ddc.zip",
                "sha256": "ac2c05db82f6a407f3dbdf0ff8399888de94881cf21fd401333b9683057b298a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-php-parser-1.1.0.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-php-parser/zipball/1c7670dd92da864b5d019f22d9f512a6ae18b78e"
                ],
                "cacheFile": "phpstan/phpstan-php-parser/3a60f66030b521425d4ae82eb36a348495b6c779.zip",
                "sha256": "7905d6a8cef6fa2896ff7ce86ec9118addafb9a6e282553bd32957fb6de7bf85"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-phpunit-1.3.4.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-phpunit/zipball/d77af96c1aaec28f7c0293677132eaaad079e01b"
                ],
                "cacheFile": "phpstan/phpstan-phpunit/094e089a621e8a8f735c95f3823e0ca5a1fc0d47.zip",
                "sha256": "4616659fcef11c89f6c7dfd7011b382624e816ec3287e0213c23cd5c2623af0f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpstan_phpstan-strict-rules-1.4.5.0",
                "urls": [
                    "https://api.github.com/repos/phpstan/phpstan-strict-rules/zipball/361f75b06066f3fdaba87c1f57bdb1ffc28d6f1d"
                ],
                "cacheFile": "phpstan/phpstan-strict-rules/a61fa77a7a0b3524e0a2ea685491e897818d534b.zip",
                "sha256": "506bc225e063b457682b0b4742ff5bc0900201702dd963ea731e06b1bd001eea"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-code-coverage-9.2.24.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-code-coverage/zipball/2cf940ebc6355a9d430462811b5aaa308b174bed"
                ],
                "cacheFile": "phpunit/php-code-coverage/22950ed3ec19594703b2c51ce0c35f7e8c502d87.zip",
                "sha256": "ea8717edadc67bd1817b2d4a79cedc7e5540b0ff3ae984655df32dc6b13bb2d2"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-file-iterator-3.0.6.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-file-iterator/zipball/cf1c2e7c203ac650e352f4cc675a7021e7d1b3cf"
                ],
                "cacheFile": "phpunit/php-file-iterator/4fd4ef934d9b090aff1c14e5987f251c5d6b2d0c.zip",
                "sha256": "d9b2fe0929a3a844490dd9d32dbbd09a19713e3356e0199b26bc0c181c6a0790"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-invoker-3.1.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-invoker/zipball/5a10147d0aaf65b58940a0b72f71c9ac0423cc67"
                ],
                "cacheFile": "phpunit/php-invoker/18d90380b8ff6f566265ca070b4bcfe4c4bbd34c.zip",
                "sha256": "d091fc2206ce86ff8664068b04952c8d8ff6dc12b7d864c1a8bf92c4adb416ef"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-text-template-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-text-template/zipball/5da5f67fc95621df9ff4c4e5a84d6a8a2acf7c28"
                ],
                "cacheFile": "phpunit/php-text-template/b8d58f7d3789d6fd84cb6a82ebcb5776ab609787.zip",
                "sha256": "98a2b504e34e4b99e433f6d738b877d5847ea9b2800f7d8534f147eebf3fc839"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_php-timer-5.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/php-timer/zipball/5a63ce20ed1b5bf577850e2c4e87f4aa902afbd2"
                ],
                "cacheFile": "phpunit/php-timer/b71ded866a460bbdb922b5eb818f4ed163f38f0c.zip",
                "sha256": "cacc8ec54d593bfaa1627bc67e110b0ef9d2f1d2ae98007d8b2bcc4fbc3f2f3c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "phpunit_phpunit-9.6.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/phpunit/zipball/e7b1615e3e887d6c719121c6d4a44b0ab9645555"
                ],
                "cacheFile": "phpunit/phpunit/43638934ebf3cb1d505efcd402ac91eee55732e5.zip",
                "sha256": "7a248a5f760d15264e4cc3b116b5234c9fb5b6f8d9a22c470e5c61d5e97eebdc"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_container-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/container/zipball/c71ecc56dfe541dbd90c5360474fbc405f8d5963"
                ],
                "cacheFile": "psr/container/a0a43e15cb16e3ab95a991e1bffc813474b15cdf.zip",
                "sha256": "3111f5b69d3a0f690f5f92d7aeacfb247f5ebd3c175088cce4b098e5d1b06ad7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_event-dispatcher-1.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/event-dispatcher/zipball/dbefd12671e8a14ec7f180cab83036ed26714bb0"
                ],
                "cacheFile": "psr/event-dispatcher/8f60a8cd1b7ff4e8f9782d70d78dee877a526529.zip",
                "sha256": "4d6a674cfd89a9957ead82e31ee4df785b2b1d215693add73184729a9a66d116"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_log-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/log/zipball/fe5ea303b0887d5caefd3d431c3e61ad47037001"
                ],
                "cacheFile": "psr/log/4109d4b3f74b78a13cb175029bcb2384f59f0a52.zip",
                "sha256": "bbc23516c85615f2f85b707bc10ba26e62033e2afd696e075575b68dc6e31928"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "psr_simple-cache-3.0.0.0",
                "urls": [
                    "https://api.github.com/repos/php-fig/simple-cache/zipball/764e0b3939f5ca87cb904f570ef9be2d78a07865"
                ],
                "cacheFile": "psr/simple-cache/f30344b376a5fb0289c0491e8df6aba973ba12aa.zip",
                "sha256": "e899e363a85c26b3f1a621182b6eed2a37a71d823410ac949a1cbfd4b655ec41"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "ramsey_collection-2.0.0.0",
                "urls": [
                    "https://api.github.com/repos/ramsey/collection/zipball/a4b48764bfbb8f3a6a4d1aeb1a35bb5e9ecac4a5"
                ],
                "cacheFile": "ramsey/collection/a31c58b47d7cbd42f269ec202a8a9f2ba07c7a37.zip",
                "sha256": "57145d32fd8950996c62f523e006e0fde49cac43b9efef49e27a08a0574eba78"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "ramsey_uuid-4.7.3.0",
                "urls": [
                    "https://api.github.com/repos/ramsey/uuid/zipball/433b2014e3979047db08a17a205f410ba3869cf2"
                ],
                "cacheFile": "ramsey/uuid/7e784b222d66ef4b7c47789873e19f004ed2c87c.zip",
                "sha256": "122dad63cf9c3c4158b72dc5c9d79dc2a2e5bcbaeff12f7fd8ff5bbade5a6dfb"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_cli-parser-1.0.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/cli-parser/zipball/442e7c7e687e42adc03470c7b668bc4b2402c0b2"
                ],
                "cacheFile": "sebastian/cli-parser/f4b297cc8d9ba3ba47f6d1c84b9d69bac882a7b1.zip",
                "sha256": "6740017ab612481526b458876d8a9aba23326099ca0e0cb7263dcd1470fb981c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-1.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit/zipball/1fc9f64c0927627ef78ba436c9b17d967e68e120"
                ],
                "cacheFile": "sebastian/code-unit/2175508c3a7c4f57c236668e95692cb4f230ef7e.zip",
                "sha256": "f51e89b8ecce2a310a2cef0d7e8256378540fe1da91daa7a25a5e50c0ae87413"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_code-unit-reverse-lookup-2.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/code-unit-reverse-lookup/zipball/ac91f01ccec49fb77bdc6fd1e548bc70f7faa3e5"
                ],
                "cacheFile": "sebastian/code-unit-reverse-lookup/68fb878dfd88a53caa52899dcad6f00ede9925b2.zip",
                "sha256": "4a6a9beb03ba89c65df74e0200eef997aed640f362a94a224e61aa3ffe5f32c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_comparator-4.0.8.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/comparator/zipball/fa0f136dd2334583309d32b62544682ee972b51a"
                ],
                "cacheFile": "sebastian/comparator/6a8576886b5e1cfd55783584d8a948ab21adc37c.zip",
                "sha256": "7ca0bc15be7811ff9964e059889466bab579a93f7ed34cd02e58f0aef85c1155"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_complexity-2.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/complexity/zipball/739b35e53379900cc9ac327b2147867b8b6efd88"
                ],
                "cacheFile": "sebastian/complexity/76ac0bc95bb26576a1588ac4917fe13f3107573f.zip",
                "sha256": "ce23bcd6c0fe24007e0ad6bf3cc17fa7beedf11dfdc6e46c84eb6b882cfa9ef8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_diff-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/diff/zipball/3461e3fccc7cfdfc2720be910d3bd73c69be590d"
                ],
                "cacheFile": "sebastian/diff/527dd851ed7cdbd6b86e440441567b594e489fde.zip",
                "sha256": "b209732f1736f8eb065781ac87b69bc0d8a752f19df0813ed820dbc60cb5c724"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_environment-5.1.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/environment/zipball/830c43a844f1f8d5b7a1f6d6076b784454d8b7ed"
                ],
                "cacheFile": "sebastian/environment/2233d3b38ac6d485959f6c153c851f07547fee65.zip",
                "sha256": "f653465ac3278f2109df985a8cfab6bb8a0524f4f0861d4e993f001b872d0408"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_exporter-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/exporter/zipball/ac230ed27f0f98f597c8a2b6eb7ac563af5e5b9d"
                ],
                "cacheFile": "sebastian/exporter/d097047a341fb0e411c70e540a62a9ca3af9479c.zip",
                "sha256": "d290d6d4c1ed86927a833cc9cceb9fefb4b55d6cda7774e38b43f28c3692dea8"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_global-state-5.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/global-state/zipball/0ca8db5a5fc9c8646244e629625ac486fa286bf2"
                ],
                "cacheFile": "sebastian/global-state/1cf3bc48e84c37ec54b03a90443ac94230cef95b.zip",
                "sha256": "e14d22f89153d22e02b21b305a34258e43992ef7ab3a2ac2517fc7b38a7259b3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_lines-of-code-1.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/lines-of-code/zipball/c1c2e997aa3146983ed888ad08b15470a2e22ecc"
                ],
                "cacheFile": "sebastian/lines-of-code/c83c674fbb96cf1b9525472250a2ec5c8e7784d6.zip",
                "sha256": "60ae97d500e9d96e826afb01b5789c511fdb7fe6304a7c325fcf84ca8a4e5e39"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-enumerator-4.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-enumerator/zipball/5c9eeac41b290a3712d88851518825ad78f45c71"
                ],
                "cacheFile": "sebastian/object-enumerator/da625947c9c4e28182677035866359692138e8aa.zip",
                "sha256": "c132dcacda3e4e0967aeabf068fa83f3f492a351c34bcd8f5101227ec01f0585"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_object-reflector-2.0.4.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/object-reflector/zipball/b4f479ebdbf63ac605d183ece17d8d7fe49c15c7"
                ],
                "cacheFile": "sebastian/object-reflector/89595d8936651649889c35a91221207e12331fda.zip",
                "sha256": "4f673297cc7e85c41c8658c202e01ead4adae48d6c870ec070941bcfb50bb53c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_recursion-context-4.0.5.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/recursion-context/zipball/e75bd0f07204fec2a0af9b0f3cfe97d05f92efc1"
                ],
                "cacheFile": "sebastian/recursion-context/4b7cea85c6a1d0a92ff75035f6b0545625890a5f.zip",
                "sha256": "8102972caec5c2041cb1b156913ac9a320cca9943dc94cde79be43e7baf6e6a9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_resource-operations-3.0.3.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/resource-operations/zipball/0f4443cb3a1d92ce809899753bc0d5d5a8dd19a8"
                ],
                "cacheFile": "sebastian/resource-operations/c70bff160e611fd40d5d68d1f06d580b9496fb3a.zip",
                "sha256": "d92f4b5b50d5e264d3b00ab31a3b80c0718f2689a1f3f23d101ce67a6e46ba5c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_type-3.2.1.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/type/zipball/75e2c2a32f5e0b3aef905b9ed0b179b953b3d7c7"
                ],
                "cacheFile": "sebastian/type/6c52c952769f461058a7bcc9db2baadd3633dfc8.zip",
                "sha256": "8507e504e5e67b8ac937a96373d980464fd8c1fa7211dd3f14fe2e2cccda6e2f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "sebastian_version-3.0.2.0",
                "urls": [
                    "https://api.github.com/repos/sebastianbergmann/version/zipball/c6c1022351a901512170118436c764e473f6de8c"
                ],
                "cacheFile": "sebastian/version/85e202da271e8389420827021d6c4f00bdd90951.zip",
                "sha256": "e1c5424e05207360f511745290144dcad1df69f1789fd97eb0d1819a145f47af"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "spatie_array-to-xml-2.17.1.0",
                "urls": [
                    "https://api.github.com/repos/spatie/array-to-xml/zipball/5cbec9c6ab17e320c58a259f0cebe88bde4a7c46"
                ],
                "cacheFile": "spatie/array-to-xml/2d0ab160be3e2ff234108c2f17ad6a074bc4116b.zip",
                "sha256": "a6fd5a96dfad96c685f963e55debd71959b27fd2f82071b91e03d724442a010c"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "squizlabs_php_codesniffer-3.7.1.0",
                "urls": [
                    "https://api.github.com/repos/squizlabs/PHP_CodeSniffer/zipball/1359e176e9307e906dc3d890bcc9603ff6d90619"
                ],
                "cacheFile": "squizlabs/php_codesniffer/87828c804599927aa873e78e73b71ea8ed2dc48e.zip",
                "sha256": "41d8bad949966238289179ca65792e9b119fcf650a0e1a1dd7e0f51cbf00eb2d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_console-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/console/zipball/3e294254f2191762c1d137aed4b94e966965e985"
                ],
                "cacheFile": "symfony/console/e0c1fc307c9477a09b9588e0c67a82d4a2831ff6.zip",
                "sha256": "3ac4ce71a9db229124258e0c7b92beeacf015c87f746cc9d37449ab175db1051"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_css-selector-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/css-selector/zipball/bf1b9d4ad8b1cf0dbde8b08e0135a2f6259b9ba1"
                ],
                "cacheFile": "symfony/css-selector/988efa8eede7b215aed9df8963121cdf57617147.zip",
                "sha256": "7d6d2c8e6f13ca973b041427d20328c2cf9b5edecc52c40c1d0939bb4ed99199"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_deprecation-contracts-3.2.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/deprecation-contracts/zipball/1ee04c65529dea5d8744774d474e7cbd2f1206d3"
                ],
                "cacheFile": "symfony/deprecation-contracts/ae67bce021ec48f10fcd4830564406f3c0d481b4.zip",
                "sha256": "c7e6575640ea31393dcf6a529534f1eef6ddfe2b29fb55a654a438a542ef9c32"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_error-handler-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/error-handler/zipball/0092696af0be8e6124b042fbe2890ca1788d7b28"
                ],
                "cacheFile": "symfony/error-handler/3d700c05656abd282415b6356b478cf3b295a83c.zip",
                "sha256": "e611e43d52bf81bfde5f088533dbd3eced269bc48e3f1dbde096b6b9990edae6"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher/zipball/f02d108b5e9fd4a6245aa73a9d2df2ec060c3e68"
                ],
                "cacheFile": "symfony/event-dispatcher/fe39a96323a6c870c77720869ec608aef72a7fb4.zip",
                "sha256": "85191ff863c7fbf59a9088f09103641e96a3007f0d099c76697233b7ecfded39"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_event-dispatcher-contracts-3.2.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/event-dispatcher-contracts/zipball/0782b0b52a737a05b4383d0df35a474303cabdae"
                ],
                "cacheFile": "symfony/event-dispatcher-contracts/5b84854b31d46922178c9a6363849dbf1884c8ca.zip",
                "sha256": "b65e7dfd381016a7c436c224ce0efef031a45226840dfbdfc1d79c7d907bf744"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_filesystem-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/filesystem/zipball/e59e8a4006afd7f5654786a83b4fcb8da98f4593"
                ],
                "cacheFile": "symfony/filesystem/78315b8fe24ac07e9264d3d2f45fe613a701c934.zip",
                "sha256": "e4c695fcf540c9280db10ab9b5613363516394bcf989489e9640a6832edd3d4a"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_finder-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/finder/zipball/c90dc446976a612e3312a97a6ec0069ab0c2099c"
                ],
                "cacheFile": "symfony/finder/b733771802f34a382644737cc1850ecf8caaf472.zip",
                "sha256": "ea883c0b7ba01d0d1f6ad2d15bdff868c84086e1fc1e2e490989bc54b5e0d7b9"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-foundation-6.2.6.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-foundation/zipball/e8dd1f502bc2b3371d05092aa233b064b03ce7ed"
                ],
                "cacheFile": "symfony/http-foundation/98239b855d9c765af67f69974dfab04e7a6f9595.zip",
                "sha256": "044b66ba25d327434c702d5c0f5059bd86e882780b3d7421d33e5408c53f6033"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_http-kernel-6.2.6.0",
                "urls": [
                    "https://api.github.com/repos/symfony/http-kernel/zipball/7122db07b0d8dbf0de682267c84217573aee3ea7"
                ],
                "cacheFile": "symfony/http-kernel/2c66373036cf4ebd6c852f883afd9555fc1925a9.zip",
                "sha256": "e6ac02a301facfcc0c8b5b6c1785bf4c102ae22efeecee8d0c3006b450f75427"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_mailer-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/mailer/zipball/29729ac0b4e5113f24c39c46746bd6afb79e0aaa"
                ],
                "cacheFile": "symfony/mailer/755fb7a4b6b7c2ff752c353bfa09d9951310f114.zip",
                "sha256": "957b6ee4a03498c8e786b4547c5b201b19d121c0528e34f60107b026f07323e5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_mime-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/mime/zipball/4b7b349f67d15cd0639955c8179a76c89f6fd610"
                ],
                "cacheFile": "symfony/mime/d908feb114a100fd19801f8e40a965008e32819e.zip",
                "sha256": "452bfc1f34de88ee3ba43d34a596dc6d7ab4b5d0efb2594e0191309a27e6cfad"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-ctype-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-ctype/zipball/5bbc823adecdae860bb64756d639ecfec17b050a"
                ],
                "cacheFile": "symfony/polyfill-ctype/04e84c03a82a82c09eaa688b17b523570f9d14d2.zip",
                "sha256": "66f212bc73088271dbbec1f3b1c3ba21171e4c5ab38676c4d151441f3e38db6f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-grapheme-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-grapheme/zipball/511a08c03c1960e08a883f4cffcacd219b758354"
                ],
                "cacheFile": "symfony/polyfill-intl-grapheme/3e0defb9f075160deb0ea7188610275ee40a9b00.zip",
                "sha256": "11c409622d2321bfdd2fd1efdbdeaaba95da5211256f6cfdb4e003d7bd7eda45"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-idn-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-idn/zipball/639084e360537a19f9ee352433b84ce831f3d2da"
                ],
                "cacheFile": "symfony/polyfill-intl-idn/c8495253150c4daacaf90487f77a76fc7122c16b.zip",
                "sha256": "b2ff6b6408861c6c8c486fcb3bd2109438d5d6ced9175250cfbef1e596665cc4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-intl-normalizer-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-intl-normalizer/zipball/19bd1e4fcd5b91116f14d8533c57831ed00571b6"
                ],
                "cacheFile": "symfony/polyfill-intl-normalizer/3282f96073427a186419bc5ae65aa6726d0f143b.zip",
                "sha256": "22bf30d7b50aabe1846e3ffbc03011903e05f4208d3bb49b373c4e5fe09500b5"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-mbstring-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-mbstring/zipball/8ad114f6b39e2c98a8b0e3bd907732c207c2b534"
                ],
                "cacheFile": "symfony/polyfill-mbstring/7061da8bfb2a98acfbdcaf076c3ba5f167d856cc.zip",
                "sha256": "b112101451a1f76a0cb4edd6595a5733059fd2f7a4cd4d36052526602e26a8fa"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php72-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php72/zipball/869329b1e9894268a8a61dabb69153029b7a8c97"
                ],
                "cacheFile": "symfony/polyfill-php72/3dc6f2e0efb0a915be032510852eb9fb9205577c.zip",
                "sha256": "973b3eaa88a3e4d3287b336c4a3e057feca1f9f703f05abd234a07d2105c14c0"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-php80-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-php80/zipball/7a6ff3f1959bb01aefccb463a0f2cd3d3d2fd936"
                ],
                "cacheFile": "symfony/polyfill-php80/fe4df98f0392f59ca247eec4d07f380451c09242.zip",
                "sha256": "8db38ad9c85c94ad664b89ff9ec9dd5b232dc922f6107bb356d44e9dcf6cde9b"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_polyfill-uuid-1.27.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/polyfill-uuid/zipball/f3cf1a645c2734236ed1e2e671e273eeb3586166"
                ],
                "cacheFile": "symfony/polyfill-uuid/826ec113493cd406218c5342c1c2a6449bb6f926.zip",
                "sha256": "ac1e3e9868ce26d0785126c1f900c1712dc2993a31b954b30bc7511e834150de"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_process-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/process/zipball/9ead139f63dfa38c4e4a9049cc64a8b2748c83b7"
                ],
                "cacheFile": "symfony/process/aa73382155bcf00e487f63c53469c8c8b0e65408.zip",
                "sha256": "f48f81e5ab992789d7233553582f61c4735fa5dc68b28d87347dcd8402e754a7"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_routing-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/routing/zipball/589bd742d5d03c192c8521911680fe88f61712fe"
                ],
                "cacheFile": "symfony/routing/38e0c81140904718bf36e8886b84e9f00c326853.zip",
                "sha256": "cef6f614a6e4c26be7949fb25f720a8c2daf5c23eb7f46e41654c17897ba653d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_service-contracts-3.2.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/service-contracts/zipball/aac98028c69df04ee77eb69b96b86ee51fbf4b75"
                ],
                "cacheFile": "symfony/service-contracts/934efdb6eaca0bae922a0d7a6b33c72f0155cdd3.zip",
                "sha256": "bdf3e104dd4765dcd54f57ab308ce585a1c1e19deb9f9679a9441ee5ddc0cd97"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_string-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/string/zipball/b2dac0fa27b1ac0f9c0c0b23b43977f12308d0b0"
                ],
                "cacheFile": "symfony/string/8eaa299fe3a28225f7a03c204ea3b8a9b72a7670.zip",
                "sha256": "f60b0a7a13e346f0f8a90b6d692207c53565cfa47f9edcb98583ae388702d3b4"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation/zipball/60556925a703cfbc1581cde3b3f35b0bb0ea904c"
                ],
                "cacheFile": "symfony/translation/3939f6386aec40578016c9efb54c2f8107fa8bf8.zip",
                "sha256": "14f4f0f2c007814d3634452b96f72c2218aed45934fdc9cee232f761dfefa22d"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_translation-contracts-3.2.0.0",
                "urls": [
                    "https://api.github.com/repos/symfony/translation-contracts/zipball/68cce71402305a015f8c1589bfada1280dc64fe7"
                ],
                "cacheFile": "symfony/translation-contracts/91e654b6d3791babf6a13e83165651b89bc5ff84.zip",
                "sha256": "b1a65e735e418678371bc98b68895b2fb0eea8248fdb24685b0fc6ce157b569f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_uid-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/uid/zipball/8ace895bded57d6496638c9b2d3b788e05b7395b"
                ],
                "cacheFile": "symfony/uid/b7893439c3c12cb9f3dfa0500e6a54726975e382.zip",
                "sha256": "6fbff82bea1ed8a60024776a90fb4b0cedd37ac0760ae081e6d1a7819b533f62"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "symfony_var-dumper-6.2.5.0",
                "urls": [
                    "https://api.github.com/repos/symfony/var-dumper/zipball/44b7b81749fd20c1bdf4946c041050e22bc8da27"
                ],
                "cacheFile": "symfony/var-dumper/31801adef0a32006363d17d86392454f62503fda.zip",
                "sha256": "ec63c388294be62b67bb95a5c298b21bb69f8274c19ff6b57304fe7449cd31d3"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "theseer_tokenizer-1.2.1.0",
                "urls": [
                    "https://api.github.com/repos/theseer/tokenizer/zipball/34a41e998c2183e22995f158c581e7b5e755ab9e"
                ],
                "cacheFile": "theseer/tokenizer/9c419ba4ed9d43ff57a21270f44363ad0bed22f7.zip",
                "sha256": "18d8c32441b19070ed7643321f5d3d5ee07217b991bee605cf64c979025044fd"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "tijsverkoyen_css-to-inline-styles-2.2.6.0",
                "urls": [
                    "https://api.github.com/repos/tijsverkoyen/CssToInlineStyles/zipball/c42125b83a4fa63b187fdf29f9c93cb7733da30c"
                ],
                "cacheFile": "tijsverkoyen/css-to-inline-styles/3dcc27d0fe326e27f50c5246f9de9d4562918729.zip",
                "sha256": "ad8d7e16f1217b1cd05a76460a56e0d632d960ee270291dd6c0e7cce21017332"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "vimeo_psalm-5.6.0.0",
                "urls": [
                    "https://api.github.com/repos/vimeo/psalm/zipball/e784128902dfe01d489c4123d69918a9f3c1eac5"
                ],
                "cacheFile": "vimeo/psalm/cc6eb1638a99e71b38c90a484071cc0d9d557f25.zip",
                "sha256": "c476ca6edad1cc54238b322442f730fea95e88ee917410e645001e5c8b57e728"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "vlucas_phpdotenv-5.5.0.0",
                "urls": [
                    "https://api.github.com/repos/vlucas/phpdotenv/zipball/1a7ea2afc49c3ee6d87061f5a233e3a035d0eae7"
                ],
                "cacheFile": "vlucas/phpdotenv/3768c8e216b4bb1af0c65a5a317f69502a0cefde.zip",
                "sha256": "0a08638e844488287a307fe9f5a2d2aeec0c84848dadcefab1c1ca06bbef048e"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "voku_portable-ascii-2.0.1.0",
                "urls": [
                    "https://api.github.com/repos/voku/portable-ascii/zipball/b56450eed252f6801410d810c8e1727224ae0743"
                ],
                "cacheFile": "voku/portable-ascii/d530a9779b65656e504bf4b013e19c70336ba351.zip",
                "sha256": "d45b55bc98e466a41369c4d9a034aa9721a614a7dbde30237299799361d8943f"
            },
            {
                "package": {
                    "id": -1
                },
                "type": "cache",
                "name": "webmozart_assert-1.11.0.0",
                "urls": [
                    "https://api.github.com/repos/webmozarts/assert/zipball/11cb2199493b2f8a3b53e7f19068fc6aac760991"
                ],
                "cacheFile": "webmozart/assert/b9bc0224905e92da07bc3de7d205f17c30035a88.zip",
                "sha256": "3dea7b980d4ba44fca74fbd1d068be28f1a771e1a1cb308e89b773eb83fa11a3"
            }
        ],
        "projectName": "jbboehr_phpstan-laravel-validation"
    }
  '';
  composerPath = data.composerPath or phpPackages.composer.src;
  cacheEntries = data.cacheEntries or [ ];
  localEntries = data.localEntries or [ ];

  # Shell snippet to collect all project dependencies.
  collectCacheScript = writeText "collect-cache.sh" (
    concatMapStrings
      (args: ''
        (
          cacheFile=${escapeShellArg args.cacheFile}
          cacheFilePath="$COMPOSER_CACHE_DIR/files/$cacheFile"
          mkdir -p "$(dirname "$cacheFilePath")"
          cp ${escapeShellArg (fetcher args)} "$cacheFilePath"
        )
      '')
      cacheEntries
  );

  replaceLocalPaths = writeText "replace-local-paths.sh" (
    concatMapStrings
      (args: ''
        sed -i -e "s|\"${args.string}\"|\"${args.path}\"|" composer.lock
      '')
      localEntries
  );

in
stdenv.mkDerivation {
  name = data.projectName;
  inherit src;

  # Make sure the build uses the right PHP version everywhere.
  # Also include unzip for Composer.
  buildInputs = [ php unzip ];

  # Defines the shell alias to run Composer.
  postHook = ''
    composer () {
      php "$NIX_COMPOSER_PATH" "$@"
    }
  '';

  configurePhase = ''
    runHook preConfigure

    # Set the cache directory for Composer.
    export COMPOSER_CACHE_DIR="$NIX_BUILD_TOP/.composer/cache"

    # Build the cache directory contents.
    source ${collectCacheScript}

    # Replace local package paths with their Nix store equivalent.
    source ${replaceLocalPaths}

    # Store the absolute path to Composer for the 'composer' alias.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Run normal Composer install to complete dependency installation.
    composer install -n -o

    runHook postConfigure
  '';

  buildPhase = ''
    runHook preBuild
    runHook postBuild
  '';

  installPhase = ''
    runHook preInstall

    mkdir -p $out/libexec $out/bin

    # Move the entire project to the output directory.
    mv $PWD "$out/libexec/$sourceRoot"
    cd "$out/libexec/$sourceRoot"

    # Update the path to Composer.
    export NIX_COMPOSER_PATH="$(readlink -f ${escapeShellArg composerPath})"

    # Invoke a plugin internal command to setup binaries.
    # composer nixify-install-bin "$out/bin"

    runHook postInstall
  '';

  passthru = {
    inherit php;
  };
}
